/*
 * sources.h — Bogart Linux check-updates package source table
 * Edit this file to add/remove/update tracked packages.
 * Do NOT edit update-checkv11.c for package changes.
 *
 * SRC_SKIP reasons:
 *   no-api    — no versioned API available
 *   eol       — end of life
 *   prebuilt  — binary install
 *   bundled   — version tied to another package
 *   xorg      — xorg.freedesktop.org, no clean API
 *   freedesktop — gitlab.freedesktop.org, needs GitLab API (future)
 */
#ifndef SOURCES_H
#define SOURCES_H

typedef enum {
    SRC_GITHUB      = 0,  /* api.github.com/repos/owner/repo/releases/latest  */
    SRC_GHTAG       = 1,  /* api.github.com/repos/owner/repo/tags              */
    SRC_GHREFTAG    = 2,  /* api.github.com/repos/owner/repo/git/refs/tags     */
    SRC_GNU         = 3,  /* ftp.gnu.org/gnu/PACKAGE/ — directory listing      */
    SRC_KERNEL      = 4,  /* www.kernel.org/pub/PATH/ — directory listing      */
    SRC_PYPI        = 5,  /* pypi.org/pypi/PACKAGE/json                        */
    SRC_GCRYPT      = 6,  /* gnupg.org/ftp/gcrypt/PACKAGE/ — directory listing */
    SRC_SKIP        = 7,  /* skip entirely                                      */
} SrcType;

typedef struct {
    const char *name;
    SrcType     src;
    const char *repo;    /* owner/repo, pkg name, or path depending on src */
    const char *prefix;  /* optional tag prefix filter                     */
} Source;

static const Source SOURCES[] = {
    /* ── LFS Base ──────────────────────────────────────────────────── */
    {"bash",             SRC_GNU,      "bash",                       NULL},
    {"bc",               SRC_GITHUB,   "gavinhoward/bc",             NULL},
    {"binutils",         SRC_GNU,      "binutils",                   NULL},
    {"bison",            SRC_GNU,      "bison",                      NULL},
    {"bzip2",            SRC_GITHUB,   "sourceware/bzip2",           NULL},
    {"coreutils",        SRC_GNU,      "coreutils",                  NULL},
    {"diffutils",        SRC_GNU,      "diffutils",                  NULL},
    {"expat",            SRC_GITHUB,   "libexpat/libexpat",          NULL},
    {"file",             SRC_GITHUB,   "file/file",                  "FILE5_"},
    {"findutils",        SRC_GNU,      "findutils",                  NULL},
    {"flex",             SRC_GITHUB,   "westes/flex",                NULL},
    {"gawk",             SRC_GNU,      "gawk",                       NULL},
    {"gdbm",             SRC_GNU,      "gdbm",                       NULL},
    {"gettext",          SRC_GNU,      "gettext",                    NULL},
    {"glibc",            SRC_GNU,      "glibc",                      NULL},
    {"gmp",              SRC_GNU,      "gmp",                        NULL},
    {"gperf",            SRC_GNU,      "gperf",                      NULL},
    {"grep",             SRC_GNU,      "grep",                       NULL},
    {"groff",            SRC_GNU,      "groff",                      NULL},
    {"grub",             SRC_GNU,      "grub",                       NULL},
    {"gzip",             SRC_GNU,      "gzip",                       NULL},
    {"inetutils",        SRC_GNU,      "inetutils",                  NULL},
    {"less",             SRC_GNU,      "less",                       NULL},
    {"libffi",           SRC_GITHUB,   "libffi/libffi",              NULL},
    {"libtool",          SRC_GNU,      "libtool",                    NULL},
    {"libxcrypt",        SRC_GITHUB,   "besser82/libxcrypt",         NULL},
    {"lz4",              SRC_GITHUB,   "lz4/lz4",                   NULL},
    {"m4",               SRC_GNU,      "m4",                         NULL},
    {"make",             SRC_GNU,      "make",                       NULL},
    {"meson",            SRC_GITHUB,   "mesonbuild/meson",           NULL},
    {"mpc",              SRC_GNU,      "mpc",                        NULL},
    {"mpfr",             SRC_GNU,      "mpfr",                       NULL},
    {"ncurses",          SRC_GNU,      "ncurses",                    NULL},
    {"ninja",            SRC_GITHUB,   "ninja-build/ninja",          NULL},
    {"openssl",          SRC_GITHUB,   "openssl/openssl",            NULL},
    {"patch",            SRC_GNU,      "patch",                      NULL},
    {"pcre2",            SRC_GITHUB,   "PCRE2Project/pcre2",         NULL},
    {"perl",             SRC_GHTAG,    "Perl/perl5",                 "v5.4"},
    {"pkgconf",          SRC_GITHUB,   "pkgconf/pkgconf",            NULL},
    {"python",           SRC_GHTAG,    "python/cpython",             "v3."},
    {"readline",         SRC_GNU,      "readline",                   NULL},
    {"sed",              SRC_GNU,      "sed",                        NULL},
    {"shadow",           SRC_GITHUB,   "shadow-maint/shadow",        NULL},
    {"systemd",          SRC_GITHUB,   "systemd/systemd",            NULL},
    {"tar",              SRC_GNU,      "tar",                        NULL},
    {"texinfo",          SRC_GNU,      "texinfo",                    NULL},
    {"util-linux",       SRC_GITHUB,   "util-linux/util-linux",      NULL},
    {"vim",              SRC_GHTAG,    "vim/vim",                    "v9."},
    {"which",            SRC_GNU,      "which",                      NULL},
    {"xz",               SRC_GITHUB,   "tukaani-project/xz",         NULL},
    {"zlib",             SRC_GITHUB,   "madler/zlib",                NULL},
    {"zstd",             SRC_GITHUB,   "facebook/zstd",              NULL},
    /* ── Toolchain ──────────────────────────────────────────────────── */
    {"gcc",              SRC_GNU,      "gcc",                        NULL},
    {"clangd",           SRC_GITHUB,   "llvm/llvm-project",          "llvmorg-"},
    {"llvm",             SRC_GITHUB,   "llvm/llvm-project",          "llvmorg-"},
    {"kmod",             SRC_GITHUB,   "kmod-project/kmod",          NULL},
    {"e2fsprogs",        SRC_GITHUB,   "tytso/e2fsprogs",            NULL},
    /* ── Python packaging ───────────────────────────────────────────── */
    {"cython",           SRC_PYPI,     "Cython",                     NULL},
    {"docutils",         SRC_PYPI,     "docutils",                   NULL},
    {"flit_core",        SRC_PYPI,     "flit_core",                  NULL},
    {"jinja2",           SRC_PYPI,     "Jinja2",                     NULL},
    {"markupsafe",       SRC_PYPI,     "MarkupSafe",                 NULL},
    {"packaging",        SRC_PYPI,     "packaging",                  NULL},
    {"pyyaml",           SRC_PYPI,     "PyYAML",                     NULL},
    {"setuptools",       SRC_PYPI,     "setuptools",                 NULL},
    {"wheel",            SRC_PYPI,     "wheel",                      NULL},
    /* ── GNOME (GitHub mirrors) ─────────────────────────────────────── */
    {"at-spi2-core",     SRC_GITHUB,   "GNOME/at-spi2-core",        NULL},
    {"gdk-pixbuf",       SRC_GITHUB,   "GNOME/gdk-pixbuf",          NULL},
    {"glib",             SRC_GITHUB,   "GNOME/glib",                 NULL},
    {"gobject-introspection", SRC_GITHUB, "GNOME/gobject-introspection", NULL},
    {"gtk",              SRC_GHTAG,    "GNOME/gtk",                  "3."},
    {"gtk4",             SRC_GHTAG,    "GNOME/gtk",                  "4."},
    {"json-glib",        SRC_GITHUB,   "GNOME/json-glib",            NULL},
    {"libgudev",         SRC_GITHUB,   "GNOME/libgudev",             NULL},
    {"libnotify",        SRC_GITHUB,   "GNOME/libnotify",            NULL},
    {"libsecret",        SRC_GITHUB,   "GNOME/libsecret",            NULL},
    {"libxml2",          SRC_GITHUB,   "GNOME/libxml2",              NULL},
    {"libxslt",          SRC_GITHUB,   "GNOME/libxslt",              NULL},
    {"librsvg",          SRC_GITHUB,   "GNOME/librsvg",              NULL},
    {"pango",            SRC_GITHUB,   "GNOME/pango",                NULL},
    {"pygobject",        SRC_GITHUB,   "GNOME/pygobject",            NULL},
    /* ── Security / crypto ──────────────────────────────────────────── */
    {"curl",             SRC_GITHUB,   "curl/curl",                  NULL},
    {"fail2ban",         SRC_GITHUB,   "fail2ban/fail2ban",          NULL},
    {"gnupg",            SRC_GCRYPT,   "gnupg",                      NULL},
    {"gnutls",           SRC_GCRYPT,   "gnutls/v3.8",                NULL},
    {"gpgme",            SRC_GCRYPT,   "gpgme",                      NULL},
    {"libassuan",        SRC_GCRYPT,   "libassuan",                  NULL},
    {"libgcrypt",        SRC_GCRYPT,   "libgcrypt",                  NULL},
    {"libgpg-error",     SRC_GCRYPT,   "libgpg-error",               NULL},
    {"libksba",          SRC_GCRYPT,   "libksba",                    NULL},
    {"linux-pam",        SRC_GITHUB,   "linux-pam/linux-pam",        NULL},
    {"mbedtls",          SRC_GITHUB,   "Mbed-TLS/mbedtls",           NULL},
    {"nettle",           SRC_GNU,      "nettle",                     NULL},
    {"nghttp2",          SRC_GITHUB,   "nghttp2/nghttp2",            NULL},
    {"npth",             SRC_GCRYPT,   "npth",                       NULL},
    {"openssh",          SRC_GITHUB,   "openssh/openssh-portable",   NULL},
    {"p11-kit",          SRC_GITHUB,   "p11-glue/p11-kit",           NULL},
    {"sudo",             SRC_GITHUB,   "sudo-project/sudo",          NULL},
    {"wireguard-tools",  SRC_GITHUB,   "WireGuard/wireguard-tools",  NULL},
    /* ── Pipewire / Wayland ─────────────────────────────────────────── */
    {"pipewire",         SRC_GITHUB,   "PipeWire/pipewire",          NULL},
    {"wireplumber",      SRC_GITHUB,   "PipeWire/wireplumber",       NULL},
    {"wayland",          SRC_GITHUB,   "wayland-project/wayland",    NULL},
    {"wayland-protocols",SRC_GITHUB,   "wayland-project/wayland-protocols", NULL},
    /* ── Hyprland ecosystem ─────────────────────────────────────────── */
    {"aquamarine",           SRC_GITHUB, "hyprwm/aquamarine",           NULL},
    {"hyprcursor",           SRC_GITHUB, "hyprwm/hyprcursor",           NULL},
    {"hyprgraphics",         SRC_GITHUB, "hyprwm/hyprgraphics",         NULL},
    {"hyprland",             SRC_GITHUB, "hyprwm/Hyprland",             NULL},
    {"hyprland-guiutils",    SRC_GITHUB, "hyprwm/hyprland-guiutils",    NULL},
    {"hyprland-protocols",   SRC_GITHUB, "hyprwm/hyprland-protocols",   NULL},
    {"hyprlang",             SRC_GITHUB, "hyprwm/hyprlang",             NULL},
    {"hyprlock",             SRC_GITHUB, "hyprwm/hyprlock",             NULL},
    {"hyprpaper",            SRC_GITHUB, "hyprwm/hyprpaper",            NULL},
    {"hyprtoolkit",          SRC_GITHUB, "hyprwm/hyprtoolkit",          NULL},
    {"hyprutils",            SRC_GITHUB, "hyprwm/hyprutils",            NULL},
    {"hyprwayland-scanner",  SRC_GITHUB, "hyprwm/hyprwayland-scanner",  NULL},
    {"hyprwire",             SRC_GITHUB, "hyprwm/hyprwire",             NULL},
    {"xdg-desktop-portal-hyprland", SRC_GITHUB, "hyprwm/xdg-desktop-portal-hyprland", NULL},
    /* ── Graphics / media ───────────────────────────────────────────── */
    {"dav1d",            SRC_GITHUB,   "videolan/dav1d",             NULL},
    {"ffmpeg",           SRC_GITHUB,   "FFmpeg/FFmpeg",              NULL},
    {"fdk-aac",          SRC_GITHUB,   "mstorsjo/fdk-aac",           NULL},
    {"flac",             SRC_GITHUB,   "xiph/flac",                  NULL},
    {"gstreamer",        SRC_GITHUB,   "GStreamer/gstreamer",         NULL},
    {"harfbuzz",         SRC_GITHUB,   "harfbuzz/harfbuzz",          NULL},
    {"highway",          SRC_GITHUB,   "google/highway",             NULL},
    {"imagemagick",      SRC_GITHUB,   "ImageMagick/ImageMagick",    NULL},
    {"lcms2",            SRC_GITHUB,   "mm2/Little-CMS",             NULL},
    {"libass",           SRC_GITHUB,   "libass/libass",              NULL},
    {"libjpeg-turbo",    SRC_GITHUB,   "libjpeg-turbo/libjpeg-turbo",NULL},
    {"libjxl",           SRC_GITHUB,   "libjxl/libjxl",             NULL},
    {"libogg",           SRC_GITHUB,   "xiph/ogg",                   NULL},
    {"libplacebo",       SRC_GITHUB,   "haasn/libplacebo",           NULL},
    {"libpng",           SRC_GITHUB,   "pnggroup/libpng",            NULL},
    {"libsndfile",       SRC_GITHUB,   "libsndfile/libsndfile",      NULL},
    {"libvorbis",        SRC_GITHUB,   "xiph/vorbis",                NULL},
    {"libvpx",           SRC_GITHUB,   "webmproject/libvpx",         NULL},
    {"libwebp",          SRC_GITHUB,   "webmproject/libwebp",        NULL},
    {"mpv",              SRC_GITHUB,   "mpv-player/mpv",             NULL},
    {"mpv-mpris",        SRC_GITHUB,   "hoyon/mpv-mpris",            NULL},
    {"nv-codec-headers", SRC_GITHUB,   "FFmpeg/nv-codec-headers",    NULL},
    {"nvidia-vaapi-driver", SRC_GITHUB,"elFarto/nvidia-vaapi-driver", NULL},
    {"openjpeg",         SRC_GITHUB,   "uclouvain/openjpeg",         NULL},
    {"opus",             SRC_GITHUB,   "xiph/opus",                  NULL},
    {"orc",              SRC_GITHUB,   "GStreamer/orc",              NULL},
    {"shaderc",          SRC_GITHUB,   "google/shaderc",             NULL},
    {"speex",            SRC_GITHUB,   "xiph/speex",                 NULL},
    {"speexdsp",         SRC_GITHUB,   "xiph/speexdsp",              NULL},
    {"spirv-headers",    SRC_GITHUB,   "KhronosGroup/SPIRV-Headers",  NULL},
    {"spirv-tools",      SRC_GITHUB,   "KhronosGroup/SPIRV-Tools",   NULL},
    {"svt-av1",          SRC_GITHUB,   "AOMediaCodec/SVT-AV1",       NULL},
    {"vulkan-headers",   SRC_GITHUB,   "KhronosGroup/Vulkan-Headers", NULL},
    {"vulkan-loader",    SRC_GITHUB,   "KhronosGroup/Vulkan-Loader",  NULL},
    {"vulkan-tools",     SRC_GITHUB,   "KhronosGroup/Vulkan-Tools",  NULL},
    {"x264",             SRC_GHTAG,    "mirror/x264",                NULL},
    {"libliftoff",       SRC_GITHUB,   "emersion/libliftoff",        NULL},
    /* ── Desktop / UI ───────────────────────────────────────────────── */
    {"alacritty",        SRC_GITHUB,   "alacritty/alacritty",        NULL},
    {"appstream",        SRC_GITHUB,   "ximion/appstream",           NULL},
    {"asciidoc",         SRC_GITHUB,   "asciidoc/asciidoc",          NULL},
    {"assimp",           SRC_GITHUB,   "assimp/assimp",              NULL},
    {"btop",             SRC_GITHUB,   "aristocratos/btop",          NULL},
    {"cava",             SRC_GITHUB,   "karlstav/cava",              NULL},
    {"chafa",            SRC_GITHUB,   "hpjansson/chafa",            NULL},
    {"cmake",            SRC_GITHUB,   "Kitware/CMake",              NULL},
    {"doxygen",          SRC_GITHUB,   "doxygen/doxygen",            NULL},
    {"fastfetch",        SRC_GITHUB,   "fastfetch-cli/fastfetch",    NULL},
    {"ffmpegthumbnailer",SRC_GITHUB,   "dirkvdb/ffmpegthumbnailer",  NULL},
    {"flatpak",          SRC_GITHUB,   "flatpak/flatpak",            NULL},
    {"freetype",         SRC_GITHUB,   "freetype/freetype",          NULL},
    {"fzf",              SRC_GITHUB,   "junegunn/fzf",               NULL},
    {"girara",           SRC_GITHUB,   "pwmt/girara",                NULL},
    {"git",              SRC_GHTAG,    "git/git",                    NULL},
    {"glaze",            SRC_GITHUB,   "stephenberry/glaze",         NULL},
    {"glm",              SRC_GITHUB,   "g-truc/glm",                 NULL},
    {"glslang",          SRC_GITHUB,   "KhronosGroup/glslang",       NULL},
    {"go",               SRC_GHREFTAG, "golang/go",                  "go1."},
    {"grim",             SRC_GITHUB,   "emersion/grim",              NULL},
    {"gtk4-layer-shell", SRC_GITHUB,   "wmww/gtk4-layer-shell",      NULL},
    {"hardinfo2",        SRC_GITHUB,   "hardinfo2/hardinfo2",        "release-"},
    {"inotify-tools",    SRC_GITHUB,   "inotify-tools/inotify-tools",NULL},
    {"iniparser",        SRC_GHTAG,    "ndevilla/iniparser",         NULL},
    {"ironbar",          SRC_GITHUB,   "JakeStanger/ironbar",        NULL},
    {"jq",               SRC_GITHUB,   "jqlang/jq",                  NULL},
    {"kitty",            SRC_GITHUB,   "kovidgoyal/kitty",           NULL},
    {"libarchive",       SRC_GITHUB,   "libarchive/libarchive",      NULL},
    {"libical",          SRC_GITHUB,   "libical/libical",            NULL},
    {"libostree",        SRC_GITHUB,   "ostreedev/ostree",           NULL},
    {"lynis",            SRC_GITHUB,   "CISOfy/lynis",               NULL},
    {"make-ca",          SRC_GITHUB,   "lfs-book/make-ca",           NULL},
    {"mako",             SRC_GITHUB,   "emersion/mako",              NULL},
    {"ncpamixer",        SRC_GHTAG,    "fulhax/ncpamixer",           NULL},
    {"nlohmann-json",    SRC_GITHUB,   "nlohmann/json",              NULL},
    {"nvme-cli",         SRC_GITHUB,   "linux-nvme/nvme-cli",        NULL},
    {"porg",             SRC_GHTAG,    "drfiemost/porg",             NULL},
    {"ps_mem",           SRC_GHTAG,    "pixelb/ps_mem",              NULL},
    {"qt6",              SRC_GHTAG,    "qt/qtbase",                  "v6."},
    {"re2",              SRC_GITHUB,   "google/re2",                 NULL},
    {"rofi-wayland",     SRC_GITHUB,   "lbonn/rofi",                 NULL},
    {"sdbus-cpp",        SRC_GITHUB,   "Kistler-Group/sdbus-cpp",    NULL},
    {"sdl3",             SRC_GITHUB,   "libsdl-org/SDL",             NULL},
    {"slurp",            SRC_GITHUB,   "emersion/slurp",             NULL},
    {"snapper",          SRC_GITHUB,   "openSUSE/snapper",           NULL},
    {"swayimg",          SRC_GITHUB,   "artemsen/swayimg",           NULL},
    {"swww",             SRC_GITHUB,   "LGFae/swww",                 NULL},
    {"tailscale",        SRC_GITHUB,   "tailscale/tailscale",        NULL},
    {"tomlplusplus",     SRC_GITHUB,   "marzer/tomlplusplus",        NULL},
    {"udis86",           SRC_GHTAG,    "vmt/udis86",                 NULL},
    {"usbguard",         SRC_GITHUB,   "USBGuard/usbguard",          NULL},
    {"waypaper",         SRC_GITHUB,   "anufrievroman/waypaper",     NULL},
    {"wlr-randr",        SRC_GITHUB,   "emersion/wlr-randr",         NULL},
    {"xdg-desktop-portal",SRC_GITHUB,  "flatpak/xdg-desktop-portal", NULL},
    {"xxhash",           SRC_GITHUB,   "Cyan4973/xxHash",            NULL},
    {"yad",              SRC_GITHUB,   "v1cont/yad",                 NULL},
    {"yazi",             SRC_GITHUB,   "sxyazi/yazi",                NULL},
    {"yt-dlp",           SRC_GITHUB,   "yt-dlp/yt-dlp",             NULL},
    {"zathura",          SRC_GITHUB,   "pwmt/zathura",               NULL},
    {"zathura-pdf-poppler",SRC_GITHUB, "pwmt/zathura-pdf-poppler",   NULL},
    {"zig",              SRC_GITHUB,   "ziglang/zig",                NULL},
    /* ── System tools ───────────────────────────────────────────────── */
    {"abseil-cpp",       SRC_GITHUB,   "abseil/abseil-cpp",          NULL},
    {"agg",              SRC_GITHUB,   "asciinema/agg",              NULL},
    {"asciinema",        SRC_GITHUB,   "asciinema/asciinema",        NULL},
    {"audit-userspace",  SRC_GITHUB,   "linux-audit/audit-userspace",NULL},
    {"autoconf",         SRC_GNU,      "autoconf",                   NULL},
    {"automake",         SRC_GNU,      "automake",                   NULL},
    {"bash-completion",  SRC_GITHUB,   "scop/bash-completion",       NULL},
    {"boost",            SRC_GITHUB,   "boostorg/boost",             NULL},
    {"brotli",           SRC_GITHUB,   "google/brotli",              NULL},
    {"btrfs-progs",      SRC_GITHUB,   "kdave/btrfs-progs",          NULL},
    {"bubblewrap",       SRC_GITHUB,   "containers/bubblewrap",      NULL},
    {"cpio",             SRC_GNU,      "cpio",                       NULL},
    {"duf",              SRC_GITHUB,   "muesli/duf",                 NULL},
    {"efibootmgr",       SRC_GITHUB,   "rhboot/efibootmgr",          NULL},
    {"exfatprogs",       SRC_GITHUB,   "exfatprogs/exfatprogs",      NULL},
    {"extra-cmake-modules",SRC_GITHUB, "KDE/extra-cmake-modules",    NULL},
    {"fftw",             SRC_GITHUB,   "FFTW/fftw3",                 NULL},
    {"gdb",              SRC_GNU,      "gdb",                        NULL},
    {"icu",              SRC_GITHUB,   "unicode-org/icu",            NULL},
    {"iproute2",         SRC_GITHUB,   "iproute2/iproute2",          NULL},
    {"kbd",              SRC_GITHUB,   "legionus/kbd",               NULL},
    {"libcap",           SRC_GITHUB,   "nicowillis/libcap",          NULL},
    {"libfyaml",         SRC_GITHUB,   "pantoniou/libfyaml",         NULL},
    {"libidn2",          SRC_GNU,      "libidn2",                    NULL},
    {"libnl",            SRC_GITHUB,   "thom311/libnl",              NULL},
    {"libnvme",          SRC_GITHUB,   "linux-nvme/libnvme",         NULL},
    {"libpsl",           SRC_GITHUB,   "rockdaboot/libpsl",          NULL},
    {"libpwquality",     SRC_GITHUB,   "libpwquality/libpwquality",  NULL},
    {"libqb",            SRC_GITHUB,   "ClusterLabs/libqb",          NULL},
    {"libseccomp",       SRC_GITHUB,   "seccomp/libseccomp",         NULL},
    {"libslirp",         SRC_GITHUB,   "nicowillis/libslirp",        NULL},
    {"libtasn1",         SRC_GNU,      "libtasn1",                   NULL},
    {"libunistring",     SRC_GNU,      "libunistring",               NULL},
    {"libusb",           SRC_GITHUB,   "libusb/libusb",              NULL},
    {"libzip",           SRC_GITHUB,   "nih-at/libzip",              NULL},
    {"muparser",         SRC_GITHUB,   "beltoforion/muparser",       NULL},
    {"nano",             SRC_GNU,      "nano",                       NULL},
    {"nasm",             SRC_GITHUB,   "netwide-assembler/nasm",     NULL},
    {"pciutils",         SRC_GITHUB,   "pciutils/pciutils",          NULL},
    {"playerctl",        SRC_GITHUB,   "altdesktop/playerctl",       NULL},
    {"polkit",           SRC_GITHUB,   "polkit-org/polkit",          NULL},
    {"procps-ng",        SRC_GITHUB,   "warmchang/procps",           NULL},
    {"protobuf",         SRC_GITHUB,   "protocolbuffers/protobuf",   NULL},
    {"pugixml",          SRC_GITHUB,   "zeux/pugixml",               NULL},
    {"scdoc",            SRC_GITHUB,   "emersion/scdoc",             NULL},
    {"seatd",            SRC_GITHUB,   "kennylevinsen/seatd",        NULL},
    {"squashfs-tools",   SRC_GITHUB,   "plougher/squashfs-tools",    NULL},
    {"swig",             SRC_GITHUB,   "swig/swig",                  NULL},
    {"sysstat",          SRC_GITHUB,   "sysstat/sysstat",            NULL},
    {"usbutils",         SRC_GITHUB,   "gregkh/usbutils",            NULL},
    {"v4l-utils",        SRC_GITHUB,   "nicowillis/v4l-utils",       NULL},
    {"wget",             SRC_GNU,      "wget",                       NULL},
    {"yasm",             SRC_GITHUB,   "yasm/yasm",                  NULL},
    /* ── Skip: xorg ─────────────────────────────────────────────────── */
    {"encodings",        SRC_SKIP,     NULL, NULL},
    {"font-adobe-utopia-type1",SRC_SKIP,NULL,NULL},
    {"font-alias",       SRC_SKIP,     NULL, NULL},
    {"font-bh-ttf",      SRC_SKIP,     NULL, NULL},
    {"font-bh-type1",    SRC_SKIP,     NULL, NULL},
    {"font-ibm-type1",   SRC_SKIP,     NULL, NULL},
    {"font-misc-ethiopic",SRC_SKIP,    NULL, NULL},
    {"font-util",        SRC_SKIP,     NULL, NULL},
    {"font-xfree86-type1",SRC_SKIP,    NULL, NULL},
    {"libfontenc",       SRC_SKIP,     NULL, NULL},
    {"libice",           SRC_SKIP,     NULL, NULL},
    {"libsm",            SRC_SKIP,     NULL, NULL},
    {"libx11",           SRC_SKIP,     NULL, NULL},
    {"libxau",           SRC_SKIP,     NULL, NULL},
    {"libxaw",           SRC_SKIP,     NULL, NULL},
    {"libxcb",           SRC_SKIP,     NULL, NULL},
    {"libxcomposite",    SRC_SKIP,     NULL, NULL},
    {"libxcursor",       SRC_SKIP,     NULL, NULL},
    {"libxcvt",          SRC_SKIP,     NULL, NULL},
    {"libxdamage",       SRC_SKIP,     NULL, NULL},
    {"libxdmcp",         SRC_SKIP,     NULL, NULL},
    {"libxext",          SRC_SKIP,     NULL, NULL},
    {"libxfixes",        SRC_SKIP,     NULL, NULL},
    {"libxfont2",        SRC_SKIP,     NULL, NULL},
    {"libxft",           SRC_SKIP,     NULL, NULL},
    {"libxi",            SRC_SKIP,     NULL, NULL},
    {"libxinerama",      SRC_SKIP,     NULL, NULL},
    {"libxkbcommon",     SRC_SKIP,     NULL, NULL},
    {"libxkbfile",       SRC_SKIP,     NULL, NULL},
    {"libxmu",           SRC_SKIP,     NULL, NULL},
    {"libxpm",           SRC_SKIP,     NULL, NULL},
    {"libxpresent",      SRC_SKIP,     NULL, NULL},
    {"libxrandr",        SRC_SKIP,     NULL, NULL},
    {"libxrender",       SRC_SKIP,     NULL, NULL},
    {"libxres",          SRC_SKIP,     NULL, NULL},
    {"libxscrnsaver",    SRC_SKIP,     NULL, NULL},
    {"libxshmfence",     SRC_SKIP,     NULL, NULL},
    {"libxt",            SRC_SKIP,     NULL, NULL},
    {"libxtst",          SRC_SKIP,     NULL, NULL},
    {"libxv",            SRC_SKIP,     NULL, NULL},
    {"libxvmc",          SRC_SKIP,     NULL, NULL},
    {"libxxf86dga",      SRC_SKIP,     NULL, NULL},
    {"libxxf86vm",       SRC_SKIP,     NULL, NULL},
    {"mkfontscale",      SRC_SKIP,     NULL, NULL},
    {"util-macros",      SRC_SKIP,     NULL, NULL},
    {"xcb-proto",        SRC_SKIP,     NULL, NULL},
    {"xcb-util",         SRC_SKIP,     NULL, NULL},
    {"xcb-util-cursor",  SRC_SKIP,     NULL, NULL},
    {"xcb-util-errors",  SRC_SKIP,     NULL, NULL},
    {"xcb-util-image",   SRC_SKIP,     NULL, NULL},
    {"xcb-util-keysyms", SRC_SKIP,     NULL, NULL},
    {"xcb-util-renderutil",SRC_SKIP,   NULL, NULL},
    {"xcb-util-wm",      SRC_SKIP,     NULL, NULL},
    {"xcursor-themes",   SRC_SKIP,     NULL, NULL},
    {"xcursorgen",       SRC_SKIP,     NULL, NULL},
    {"xkbcomp",          SRC_SKIP,     NULL, NULL},
    {"xkeyboard-config", SRC_SKIP,     NULL, NULL},
    {"xorg-server",      SRC_SKIP,     NULL, NULL},
    {"xorgproto",        SRC_SKIP,     NULL, NULL},
    {"xrandr",           SRC_SKIP,     NULL, NULL},
    {"xtrans",           SRC_SKIP,     NULL, NULL},
    {"xwayland",         SRC_SKIP,     NULL, NULL},
    /* ── Skip: freedesktop (needs GitLab API — future) ──────────────── */
    {"bluez",            SRC_SKIP,     NULL, NULL},
    {"cairo",            SRC_SKIP,     NULL, NULL},
    {"dbus",             SRC_SKIP,     NULL, NULL},
    {"desktop-file-utils",SRC_SKIP,    NULL, NULL},
    {"egl-gbm",          SRC_SKIP,     NULL, NULL},
    {"egl-wayland",      SRC_SKIP,     NULL, NULL},
    {"egl-x11",          SRC_SKIP,     NULL, NULL},
    {"eglexternalplatform",SRC_SKIP,   NULL, NULL},
    {"fontconfig",       SRC_SKIP,     NULL, NULL},
    {"glu",              SRC_SKIP,     NULL, NULL},
    {"libdecor",         SRC_SKIP,     NULL, NULL},
    {"libdisplay-info",  SRC_SKIP,     NULL, NULL},
    {"libdrm",           SRC_SKIP,     NULL, NULL},
    {"libepoxy",         SRC_SKIP,     NULL, NULL},
    {"libevdev",         SRC_SKIP,     NULL, NULL},
    {"libglvnd",         SRC_SKIP,     NULL, NULL},
    {"libinput",         SRC_SKIP,     NULL, NULL},
    {"libpciaccess",     SRC_SKIP,     NULL, NULL},
    {"mesa",             SRC_SKIP,     NULL, NULL},
    {"pixman",           SRC_SKIP,     NULL, NULL},
    {"poppler",          SRC_SKIP,     NULL, NULL},
    {"shared-mime-info", SRC_SKIP,     NULL, NULL},
    {"spice",            SRC_SKIP,     NULL, NULL},
    {"spice-protocol",   SRC_SKIP,     NULL, NULL},
    {"upower",           SRC_SKIP,     NULL, NULL},
    {"virglrenderer",    SRC_SKIP,     NULL, NULL},
    /* ── Skip: no clean API ─────────────────────────────────────────── */
    {"acl",              SRC_SKIP,     NULL, NULL},
    {"acpica",           SRC_SKIP,     NULL, NULL},
    {"alsa-lib",         SRC_SKIP,     NULL, NULL},
    {"alsa-utils",       SRC_SKIP,     NULL, NULL},
    {"attr",             SRC_SKIP,     NULL, NULL},
    {"autoconf-archive", SRC_SKIP,     NULL, NULL},
    {"cracklib",         SRC_SKIP,     NULL, NULL},
    {"dejagnu",          SRC_SKIP,     NULL, NULL},
    {"dmidecode",        SRC_SKIP,     NULL, NULL},
    {"dosfstools",       SRC_SKIP,     NULL, NULL},
    {"dracut",           SRC_SKIP,     NULL, NULL},
    {"dtc",              SRC_SKIP,     NULL, NULL},
    {"duktape",          SRC_SKIP,     NULL, NULL},
    {"efivar",           SRC_SKIP,     NULL, NULL},
    {"exfatprogs",       SRC_GITHUB,   "exfatprogs/exfatprogs",      NULL},
    {"expect5",          SRC_SKIP,     NULL, NULL},
    {"fribidi",          SRC_SKIP,     NULL, NULL},
    {"fuse",             SRC_SKIP,     NULL, NULL},
    {"glib-networking",  SRC_SKIP,     NULL, NULL},
    {"gobject-introspection", SRC_GITHUB, "GNOME/gobject-introspection", NULL},
    {"graphene",         SRC_SKIP,     NULL, NULL},
    {"graphite2",        SRC_SKIP,     NULL, NULL},
    {"grub-btrfs",       SRC_SKIP,     NULL, NULL},
    {"gsettings-desktop-schemas",SRC_SKIP,NULL,NULL},
    {"gst-libav",        SRC_SKIP,     NULL, NULL},
    {"gst-plugins-bad",  SRC_SKIP,     NULL, NULL},
    {"gst-plugins-base", SRC_SKIP,     NULL, NULL},
    {"gst-plugins-good", SRC_SKIP,     NULL, NULL},
    {"gst-plugins-ugly", SRC_SKIP,     NULL, NULL},
    {"hicolor-icon-theme",SRC_SKIP,    NULL, NULL},
    {"hwdata",           SRC_SKIP,     NULL, NULL},
    {"iana-etc",         SRC_SKIP,     NULL, NULL},
    {"inih",             SRC_SKIP,     NULL, NULL},
    {"intltool",         SRC_SKIP,     NULL, NULL},
    {"iso-codes",        SRC_SKIP,     NULL, NULL},
    {"itstool",          SRC_SKIP,     NULL, NULL},
    {"iwd",              SRC_SKIP,     NULL, NULL},
    {"jansson",          SRC_SKIP,     NULL, NULL},
    {"json-c",           SRC_SKIP,     NULL, NULL},
    {"lame",             SRC_SKIP,     NULL, NULL},
    {"libapparmor",      SRC_SKIP,     NULL, NULL},
    {"libcap-ng",        SRC_SKIP,     NULL, NULL},
    {"libndp",           SRC_SKIP,     NULL, NULL},
    {"libpipeline",      SRC_SKIP,     NULL, NULL},
    {"libsoup",          SRC_SKIP,     NULL, NULL},
    {"libtiff",          SRC_SKIP,     NULL, NULL},
    {"libtirpc",         SRC_SKIP,     NULL, NULL},
    {"libva",            SRC_SKIP,     NULL, NULL},
    {"libva-utils",      SRC_SKIP,     NULL, NULL},
    {"linux-firmware",   SRC_SKIP,     NULL, NULL},
    {"lua",              SRC_SKIP,     NULL, NULL},
    {"luajit",           SRC_SKIP,     NULL, NULL},
    {"lzo",              SRC_SKIP,     NULL, NULL},
    {"man-db",           SRC_SKIP,     NULL, NULL},
    {"man-pages",        SRC_SKIP,     NULL, NULL},
    {"mesa-demos",       SRC_SKIP,     NULL, NULL},
    {"mpg123",           SRC_SKIP,     NULL, NULL},
    {"mtdev",            SRC_SKIP,     NULL, NULL},
    {"ncdu",             SRC_SKIP,     NULL, NULL},
    {"net-tools",        SRC_SKIP,     NULL, NULL},
    {"noto-cjk",         SRC_SKIP,     NULL, NULL},
    {"perl-file-sharedir-install",SRC_SKIP,NULL,NULL},
    {"poppler-data",     SRC_SKIP,     NULL, NULL},
    {"popt",             SRC_SKIP,     NULL, NULL},
    {"psmisc",           SRC_SKIP,     NULL, NULL},
    {"pulseaudio",       SRC_SKIP,     NULL, NULL},
    {"qemu",             SRC_SKIP,     NULL, NULL},
    {"qrcodegencpp",     SRC_SKIP,     NULL, NULL},
    {"qt5",              SRC_SKIP,     NULL, NULL},
    {"rtkit",            SRC_SKIP,     NULL, NULL},
    {"sdl2-compat",      SRC_SKIP,     NULL, NULL},
    {"simde",            SRC_SKIP,     NULL, NULL},
    {"socat",            SRC_SKIP,     NULL, NULL},
    {"sqlite-autoconf",  SRC_SKIP,     NULL, NULL},
    {"startup-notification",SRC_SKIP,  NULL, NULL},
    {"tcl8",             SRC_SKIP,     NULL, NULL},
    {"usbutils",         SRC_GITHUB,   "gregkh/usbutils",            NULL},
    {"v4l-utils",        SRC_SKIP,     NULL, NULL},
    {"websocketpp",      SRC_SKIP,     NULL, NULL},
    {"wireless-regdb",   SRC_SKIP,     NULL, NULL},
    {"x265",             SRC_SKIP,     NULL, NULL},
    {"xdg-dbus-proxy",   SRC_SKIP,     NULL, NULL},
    {"xdg-desktop-portal-wlr",SRC_SKIP,NULL, NULL},
    {"xdg-user-dirs",    SRC_SKIP,     NULL, NULL},
    {"xml-parser",       SRC_SKIP,     NULL, NULL},
    {"xorriso",          SRC_SKIP,     NULL, NULL},
    {"yaml",             SRC_SKIP,     NULL, NULL},
    {NULL, 0, NULL, NULL}
};

#endif /* SOURCES_H */
