#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "graph.h"

Graph *graph_new(void) {
    Graph *g   = calloc(1, sizeof(Graph));
    g->capacity = 4096;
    g->entries  = calloc(g->capacity, sizeof(GraphEntry));
    return g;
}

void graph_free(Graph *g) {
    if (!g) return;
    free(g->entries);
    free(g);
}

void graph_add(Graph *g, EntryType type, const char *pkg, const char *soname) {
    if (g->count >= g->capacity) {
        g->capacity *= 2;
        g->entries   = realloc(g->entries, g->capacity * sizeof(GraphEntry));
    }
    GraphEntry *e = &g->entries[g->count++];
    e->type = type;
    strncpy(e->pkg,    pkg,    MAX_PKGNAME - 1); e->pkg[MAX_PKGNAME - 1]   = '\0';
    strncpy(e->soname, soname, MAX_SONAME  - 1); e->soname[MAX_SONAME - 1] = '\0';
}

int graph_has(Graph *g, EntryType type, const char *pkg, const char *soname) {
    for (int i = 0; i < g->count; i++) {
        GraphEntry *e = &g->entries[i];
        if (e->type == type &&
            strcmp(e->pkg,    pkg)    == 0 &&
            strcmp(e->soname, soname) == 0)
            return 1;
    }
    return 0;
}

int graph_write(const Graph *g, const char *path) {
    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "bogartgraph: cannot write %s: %s\n",
                path, strerror(errno));
        return -1;
    }
    fprintf(f, "# bogartpkg-graph.db — generated by bogartgraph\n");
    fprintf(f, "# PROVIDES <pkg> <soname>\n");
    fprintf(f, "# NEEDS    <pkg> <soname>\n\n");
    for (int i = 0; i < g->count; i++) {
        const GraphEntry *e = &g->entries[i];
        fprintf(f, "%s %s %s\n",
                e->type == ENTRY_PROVIDES ? "PROVIDES" : "NEEDS",
                e->pkg, e->soname);
    }
    fclose(f);
    return 0;
}

Graph *graph_load(const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) return NULL;

    Graph *g = graph_new();
    char   line[MAX_LINE];
    while (fgets(line, sizeof(line), f)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        char type_s[16], pkg[MAX_PKGNAME], soname[MAX_SONAME];
        if (sscanf(line, "%15s %63s %127s", type_s, pkg, soname) != 3) continue;
        EntryType t;
        if      (strcmp(type_s, "PROVIDES") == 0) t = ENTRY_PROVIDES;
        else if (strcmp(type_s, "NEEDS")    == 0) t = ENTRY_NEEDS;
        else continue;
        graph_add(g, t, pkg, soname);
    }
    fclose(f);
    return g;
}
