PKG_NAME="acl"
PKG_VER="2.3.2"
PKG_URL1="https://download.savannah.gnu.org/releases/acl/acl-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS="--disable-static --docdir=/usr/share/doc/acl-${PKG_VER}"
PKG_SHA256="97203a72cae99ab89a067fe2210c1cbf052bc492b479eca7d226d9830883b0bd"
