PKG_NAME="acpica"
PKG_VER="20251212"
PKG_URL1="https://github.com/open-acpica/acpica/releases/download/${PKG_VER}/acpica-unix2-${PKG_VER}.tar.gz"
PKG_TARBALL="acpica-unix2-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make NOWERROR=TRUE"
PKG_CUSTOM_INSTALL="make install PREFIX=/usr"
