PKG_NAME="agg"
PKG_VER="1.9.0"
PKG_URL1="https://github.com/asciinema/agg/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -m755 target/release/agg /usr/bin/agg"
