PKG_NAME="alacritty"
PKG_VER="0.17.0"
PKG_URL1="https://github.com/alacritty/alacritty/archive/refs/tags/v${PKG_VER}/alacritty-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -Dm755 target/release/alacritty /usr/bin/alacritty
install -Dm644 extra/linux/Alacritty.desktop /usr/share/applications/Alacritty.desktop
install -Dm644 extra/completions/alacritty.bash /usr/share/bash-completion/completions/alacritty
install -Dm644 extra/man/alacritty.1.gz /usr/share/man/man1/alacritty.1.gz
tic -xe alacritty,alacritty-direct extra/alacritty.info"
