PKG_NAME="alsa-utils"
PKG_VER="1.2.16"
PKG_URL1="https://www.alsa-project.org/files/pub/utils/alsa-utils-${PKG_VER}.tar.bz2"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-alsaconf --disable-bat --disable-xmlto --with-curses=ncursesw"
