PKG_NAME="alsa-lib"
PKG_VER="1.2.16"
PKG_URL1="https://www.alsa-project.org/files/pub/lib/alsa-lib-${PKG_VER}.tar.bz2"
PKG_BUILD_TYPE="autotools"
PKG_SHA256="122b1e3166d55fe19bcde656535d7a36f2ab10e66c72c6ad2f43f20ffded0a96"
