PKG_NAME="android-studio"
PKG_VER="2026.1.2.10"
PKG_URL1="https://redirector.gvt1.com/edgedl/android/studio/ide-zips/${PKG_VER}/android-studio-quail2-linux.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_STRIP_COMPONENTS="1"
PKG_CUSTOM_BUILD="echo 'pre-built, skipping build'"
PKG_CUSTOM_INSTALL="rm -rf /opt/android-studio && mkdir -p /opt/android-studio && cp -Rp * /opt/android-studio/"
PKG_CASCADE_SKIP="binary-install"
