PKG_NAME="appstream"
PKG_VER="1.1.3"
PKG_URL1="https://github.com/ximion/appstream/archive/refs/tags/v${PKG_VER}/appstream-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dapidocs=false -Ddocs=false -Dinstall-docs=false -Dstemming=false -Dman=false -Dgir=false"
PKG_SRC_DIR="appstream-${PKG_VER}"
