PKG_NAME="aquamarine"
PKG_VER="0.11.0"
PKG_URL1="https://github.com/hyprwm/aquamarine/archive/refs/tags/v${PKG_VER}/aquamarine-${PKG_VER}.tar.gz"
PKG_TARBALL="aquamarine-${PKG_VER}.tar.gz"
PKG_DIR="aquamarine-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Release"
