PKG_NAME="asciinema"
PKG_VER="3.2.1"
PKG_URL1="https://github.com/asciinema/asciinema/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="asciinema-${PKG_VER}.tar.gz"
PKG_DIR="asciinema-${PKG_VER}"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -Dm755 target/release/asciinema /usr/local/bin/asciinema"
