PKG_NAME="asciidoc"
PKG_VER="10.2.1"
PKG_URL1="https://github.com/asciidoc-py/asciidoc-py/releases/download/${PKG_VER}/asciidoc-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="rm -rf /usr/lib/python3.14/site-packages/asciidoc*"
PKG_CUSTOM_BUILD="python3 setup.py build"
PKG_CUSTOM_INSTALL="python3 setup.py install --root=/ --prefix=/usr --optimize=1"
