PKG_NAME="assimp"
PKG_VER="6.0.5"
PKG_URL1="https://github.com/assimp/assimp/archive/v${PKG_VER}/assimp-${PKG_VER}.tar.gz"
PKG_TARBALL="assimp-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DASSIMP_BUILD_TESTS=OFF -DASSIMP_BUILD_SAMPLES=OFF"
