PKG_NAME="at-spi2-core"
PKG_VER="2.60.4"
PKG_URL1="https://download.gnome.org/sources/at-spi2-core/2.60/at-spi2-core-${PKG_VER}.tar.xz"
PKG_TARBALL="at-spi2-core-${PKG_VER}.tar.xz"
PKG_DIR="at-spi2-core-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="1a1f5ba9805917f41fc6aa6823dcf887a291d607a427e2d5afb6b5dfa65070c7"
