PKG_NAME="audit-userspace"
PKG_VER="4.2.1"
PKG_URL1="https://codeload.github.com/linux-audit/audit-userspace/tar.gz/refs/tags/v${PKG_VER}"
PKG_TARBALL="audit-userspace-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="autoreconf -fiv"
PKG_OPTS="--disable-static --enable-shared --with-python3 --disable-zos-remote"
