PKG_NAME="automake"
PKG_VER="1.18.1"
PKG_URL1="https://ftpmirror.gnu.org/automake/automake-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--docdir=/usr/share/doc/automake-${PKG_VER}"
PKG_SHA256="168aa363278351b89af56684448f525a5bce5079d0b6842bd910fdd3f1646887"
