PKG_NAME="aws-cli"
PKG_VER="2"
PKG_URL1="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
PKG_TARBALL="awscli-exe-linux-x86_64.zip"
PKG_STRIP_COMPONENTS="0"
PKG_SKIP_EXTRACT="1"
PKG_CASCADE_SKIP="binary-only"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="unzip -o awscli-exe-linux-x86_64.zip"
PKG_CUSTOM_INSTALL="./aws/install --install-dir /usr/local/aws-cli --bin-dir /usr/local/bin --update"
