PKG_NAME="bash"
PKG_VER="5.3.0"
PKG_URL1="https://ftpmirror.gnu.org/bash/bash-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--without-bash-malloc --with-installed-readline --docdir=/usr/share/doc/bash-${PKG_VER}"
