PKG_NAME="bash"
PKG_VER="5.3"
PKG_URL1="https://ftpmirror.gnu.org/bash/bash-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--without-bash-malloc --with-installed-readline --docdir=/usr/share/doc/bash-${PKG_VER}"
PKG_SHA256="0d5cd86965f869a26cf64f4b71be7b96f90a3ba8b3d74e27e8e9d9d5550f31ba"
