PKG_NAME="bc"
PKG_VER="7.0.3"
PKG_URL1="https://github.com/gavinhoward/bc/releases/download/${PKG_VER}/bc-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="CC='gcc -std=c99' ./configure --prefix=/usr -G -O3 -r && make"
PKG_CUSTOM_INSTALL="make install"
