PKG_NAME="binutils"
PKG_VER="2.46.0"
PKG_URL1="https://ftp.gnu.org/gnu/binutils/binutils-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-gold --enable-ld=default --enable-plugins --enable-shared --disable-werror --with-system-zlib"
