PKG_NAME="bluez"
PKG_VER="5.86"
PKG_URL1="https://www.kernel.org/pub/linux/bluetooth/bluez-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--sysconfdir=/etc --localstatedir=/var --enable-library --disable-manpages --disable-systemd LIBS=-licalvcal"
