PKG_NAME="bluez"
PKG_VER="5.86"
PKG_URL1="https://www.kernel.org/pub/linux/bluetooth/bluez-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--sysconfdir=/etc --localstatedir=/var --enable-library --disable-manpages --disable-systemd LIBS=-licalvcal"
PKG_SHA256="99f144540c6070591e4c53bcb977eb42664c62b7b36cb35a29cf72ded339621d"
