PKG_NAME="bochs"
PKG_VER="3.0"
PKG_URL1="https://codeload.github.com/bochs-emu/Bochs/tar.gz/refs/tags/REL_3_0_FINAL"
PKG_TARBALL="bochs-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_STRIP_COMPONENTS="1"
PKG_PRE_BUILD="cd bochs && libtoolize --force --copy --install && aclocal -I libltdl/m4 && autoconf"
PKG_CUSTOM_BUILD="cd bochs && ./configure --prefix=/usr --enable-debugger --enable-x86-64 --with-sdl2 && make -j$(nproc)"
PKG_CUSTOM_INSTALL="cd bochs && make install"
