PKG_NAME="boost"
PKG_VER="1.92.0"
PKG_URL1="https://github.com/boostorg/boost/releases/download/boost-${PKG_VER}/boost-${PKG_VER}-cmake.tar.xz"
PKG_TARBALL="boost-${PKG_VER}-cmake.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="./bootstrap.sh --prefix=/usr && ./b2 -j$(nproc) release"
PKG_CUSTOM_BUILD="echo 'build done in PRE_BUILD'"
PKG_CUSTOM_INSTALL="./b2 install --prefix=/usr"
