PKG_NAME="brotli"
PKG_VER="1.2.0"
PKG_URL1="https://github.com/google/brotli/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="brotli-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib"
