PKG_NAME="btrfs-progs"
PKG_VER="7.1"
PKG_URL1="https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-documentation"
PKG_PRE_BUILD="./autogen.sh"
