PKG_NAME="bubblewrap"
PKG_VER="0.11.2"
PKG_URL1="https://github.com/containers/bubblewrap/releases/download/v${PKG_VER}/bubblewrap-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false"
