PKG_NAME="bzip2"
PKG_VER="1.0.8"
PKG_URL1="https://www.sourceware.org/pub/bzip2/bzip2-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="patch -Np1 -i /sources/patches/bzip2-${PKG_VER}-install_docs-1.patch && sed -i 's@\(ln -s -f \)\$(PREFIX)/bin/@\1@' Makefile && sed -i 's@(PREFIX)/man@(PREFIX)/share/man@g' Makefile"
PKG_CUSTOM_BUILD="make -f Makefile-libbz2_so && make clean && make"
PKG_CUSTOM_INSTALL="make PREFIX=/usr install && cp -av libbz2.so.* /usr/lib && ln -sfv libbz2.so.1.0.8 /usr/lib/libbz2.so && ln -sfv libbz2.so.1.0.8 /usr/lib/libbz2.so.1 && cp -v bzip2-shared /usr/bin/bzip2 && for i in /usr/bin/{bzcat,bunzip2}; do ln -sfv bzip2 \$i; done && rm -fv /usr/lib/libbz2.a"
