PKG_NAME="cairo"
PKG_VER="1.18.4"
PKG_URL1="https://cairographics.org/releases/cairo-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dgtk_doc=false"
