PKG_NAME="cava"
PKG_VER="0.10.7"
PKG_URL1="https://github.com/karlstav/cava/releases/download/${PKG_VER}/cava-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_PRE_BUILD="echo '${PKG_VER}' > version && sed -i 's/AX_CHECK_GL/true/g' configure.ac && autoreconf -fi"

