PKG_NAME="chafa"
PKG_VER="1.18.2"
PKG_URL1="https://github.com/hpjansson/chafa/releases/download/${PKG_VER}/chafa-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SHA256="0b8d9ba9f347e8b6c0c71878217c9b0e478b4a42aa4babea0bf20840567239c2"
