PKG_NAME="clangd"
PKG_VER="22.1"
PKG_URL1="https://github.com/clangd/clangd/releases/download/${PKG_VER}.0/clangd-linux-${PKG_VER}.0.zip"
PKG_TARBALL="clangd-linux-${PKG_VER}.0.zip"
PKG_BUILD_TYPE="custom"
PKG_SKIP_EXTRACT="1"
PKG_CASCADE_SKIP="binary-only"
PKG_CUSTOM_BUILD="unzip -o ${PKG_TARBALL} -d ."
PKG_CUSTOM_INSTALL="install -m755 clangd_${PKG_VER}.0/bin/clangd /usr/bin/clangd"
