PKG_NAME="cmake"
PKG_VER="4.4.0"
PKG_URL1="https://cmake.org/files/v${PKG_VER%.*}/cmake-${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/Kitware/CMake/releases/download/v${PKG_VER}/cmake-${PKG_VER}.tar.gz"
PKG_TARBALL="cmake-${PKG_VER}.tar.gz"
PKG_DIR="cmake-${PKG_VER}"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="./bootstrap --prefix=/usr --parallel=$(nproc) -- -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF && make -j$(nproc)"
PKG_CUSTOM_INSTALL="make install"
