PKG_NAME="coreutils"
PKG_VER="9.11"
PKG_URL1="https://ftpmirror.gnu.org/coreutils/coreutils-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="patch -Np1 -i /sources/patches/coreutils-${PKG_VER}-i18n-1.patch && autoreconf -fv && automake -af"
PKG_CUSTOM_BUILD="FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr && make"
PKG_CUSTOM_INSTALL="make install && mv -v /usr/bin/chroot /usr/sbin && mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8 && sed -i 's/\"1\"/\"8\"/' /usr/share/man/man8/chroot.8"
