PKG_NAME="cpio"
PKG_VER="2.15"
PKG_URL1="https://ftp.gnu.org/gnu/cpio/cpio-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-nls"
PKG_PRE_BUILD="curl -sL 'https://git.savannah.gnu.org/cgit/cpio.git/patch/?id=f42137f5ab9cf07d1e62edc05e0212688d3ebaa2' | patch -p1"
