PKG_NAME="cracklib"
PKG_VER="2.10.3"
PKG_URL1="https://github.com/cracklib/cracklib/releases/download/v${PKG_VER}/cracklib-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
PKG_POST_INSTALL="create-cracklib-dict /usr/share/cracklib/cracklib-small"
PKG_SHA256="1d1b83676b5673051b9373e1ca0db81c1fa88faf9a195a3c1af984fd9c250d66"
