PKG_NAME="curl"
PKG_VER="8.20.0"
PKG_URL1="https://curl.se/download/curl-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --with-openssl --enable-threaded-resolver --with-ca-path=/etc/ssl/certs"
PKG_SHA256="63fe2dc148ba0ceae89922ef838f7e5c946272c2e78b7c59fab4b79d3ce2b896"
