PKG_NAME="curl"
PKG_VER="8.21.0"
PKG_URL1="https://curl.se/download/curl-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --with-openssl --enable-threaded-resolver --with-ca-path=/etc/ssl/certs"
