PKG_NAME="cython"
PKG_VER="3.2.8"
PKG_URL1="https://github.com/cython/cython/releases/download/${PKG_VER}/cython-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="python3 setup.py build"
PKG_CUSTOM_INSTALL="python3 setup.py install --prefix=/usr"
