PKG_NAME="dav1d"
PKG_VER="1.5.4"
PKG_URL1="https://code.videolan.org/videolan/dav1d/-/archive/${PKG_VER}/dav1d-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Denable_tools=true -Denable_tests=false -Dlibdir=lib64"
