PKG_NAME="dbus"
PKG_VER="1.16.2"
PKG_URL1="https://dbus.freedesktop.org/releases/dbus/dbus-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="mkdir -p build && cd build && meson setup --prefix=/usr --buildtype=release --wrap-mode=nofallback .. && ninja"
PKG_CUSTOM_INSTALL="cd build && ninja install && ln -sfv /etc/machine-id /var/lib/dbus/machine-id"
PKG_SHA256="0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"
