PKG_NAME="dejagnu"
PKG_VER="1.6.3"
PKG_URL1="https://ftpmirror.gnu.org/dejagnu/dejagnu-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="mkdir -v build"
PKG_CUSTOM_BUILD="cd build && ../configure --prefix=/usr && makeinfo --html --no-split -o doc/dejagnu.html ../doc/dejagnu.texi && makeinfo --plaintext -o doc/dejagnu.txt ../doc/dejagnu.texi"
PKG_CUSTOM_INSTALL="cd build && make install && install -v -dm755 /usr/share/doc/dejagnu-${PKG_VER} && install -v -m644 doc/dejagnu.{html,txt} /usr/share/doc/dejagnu-${PKG_VER}"
PKG_SHA256="87daefacd7958b4a69f88c6856dbd1634261963c414079d0c371f589cd66a2e3"
