PKG_NAME="desktop-file-utils"
PKG_VER="0.28"
PKG_URL1="https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/archive/${PKG_VER}/desktop-file-utils-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
