PKG_NAME="desktop-file-utils"
PKG_VER="0.28"
PKG_URL1="https://gitlab.freedesktop.org/xdg/desktop-file-utils/-/archive/${PKG_VER}/desktop-file-utils-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="379ecbc1354d0c052188bdf5dbbc4a020088ad3f9cab54487a5852d1743a4f3b"
