PKG_NAME="dmidecode"
PKG_VER="3.7"
PKG_URL1="https://download.savannah.gnu.org/releases/dmidecode/dmidecode-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make"
PKG_CUSTOM_INSTALL="make install PREFIX=/usr/local"
