PKG_NAME="dnsmasq"
PKG_VER="2.93"
PKG_URL1="https://thekelleys.org.uk/dnsmasq/dnsmasq-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make PREFIX=/usr"
PKG_CUSTOM_INSTALL="make PREFIX=/usr install"
