PKG_NAME="dosfstools"
PKG_VER="4.2"
PKG_URL1="https://github.com/dosfstools/dosfstools/releases/download/v${PKG_VER}/${PKG_NAME}-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--prefix=/usr --enable-compat-symlinks --mandir=/usr/share/man --docdir=/usr/share/doc/dosfstools-${PKG_VER}"
