PKG_NAME="doxygen"
PKG_VER="1.18.0"
PKG_URL1="https://github.com/doxygen/doxygen/releases/download/Release_${PKG_VER//\./_}/doxygen-${PKG_VER}.src.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib64 -Dbuild_doc=OFF -Dbuild_wizard=OFF"
