PKG_NAME="dracut"
PKG_VER="111"
PKG_URL1="https://github.com/dracut-ng/dracut-ng/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="dracut-${PKG_VER}.tar.gz"
PKG_DIR="dracut-ng-${PKG_VER}"
PKG_OPTS="--sysconfdir=/etc --disable-documentation"
PKG_SHA256="ca949190692e91611ef16ea3642c0f764f63948860f3f742524310728c991493"
