PKG_NAME="dtc"
PKG_VER="1.8.1"
PKG_URL1="https://github.com/dgibson/dtc/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="dtc-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dlibdir=/usr/lib -Dtests=false -Dpython=disabled -Dvalgrind=disabled"
PKG_PRE_BUILD="rm -rf /usr/lib64/libfdt* /usr/lib64/pkgconfig/libfdt.pc"
