PKG_NAME="duf"
PKG_VER="0.9.1"
PKG_URL1="https://codeload.github.com/muesli/duf/tar.gz/refs/tags/v${PKG_VER}"
PKG_TARBALL="duf-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="go build -o duf ."
PKG_CUSTOM_INSTALL="install -m755 duf /usr/local/bin/duf"
