PKG_NAME="duktape"
PKG_VER="2.7.0"
PKG_URL1="https://duktape.org/duktape-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make -f Makefile.sharedlibrary"
PKG_CUSTOM_INSTALL="make install -f Makefile.sharedlibrary INSTALL_PREFIX=/usr"
