PKG_NAME="e2fsprogs"
PKG_VER="1.47.4"
PKG_URL1="https://downloads.sourceforge.net/project/e2fsprogs/e2fsprogs/v${PKG_VER}/e2fsprogs-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="mkdir -p build && cd build && ../configure --prefix=/usr --sysconfdir=/etc --enable-elf-shlibs --disable-libblkid --disable-libuuid --disable-uuidd --disable-fsck && make"
PKG_CUSTOM_INSTALL="cd build && make install && rm -fv /usr/lib/{libcom_err,libe2p,libext2fs,libss}.a && gunzip -v /usr/share/info/libext2fs.info.gz && install-info --dir-file=/usr/share/info/dir /usr/share/info/libext2fs.info"
PKG_SHA256="2cec05f39c20ee621f14926195664e66e6017190ac8e4bbdb16d86082e43c5da"
