PKG_NAME="efibootmgr"
PKG_VER="18"
PKG_URL1="https://github.com/rhboot/efibootmgr/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="efibootmgr-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make EFIDIR=EFI"
PKG_CUSTOM_INSTALL="make install PREFIX=/usr EFIDIR=EFI"
