PKG_NAME="efivar"
PKG_VER="39"
PKG_URL1="https://github.com/rhboot/efivar/archive/39/efivar-${PKG_VER}.tar.gz"
PKG_TARBALL="efivar-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="curl -sL https://www.linuxfromscratch.org/patches/blfs/svn/efivar-39-upstream_fixes-1.patch | patch -p1"
PKG_CUSTOM_BUILD="make SUBDIRS=src"
PKG_CUSTOM_INSTALL="make install SUBDIRS=src PREFIX=/usr"
