PKG_NAME="egl-gbm"
PKG_VER="1.1.3"
PKG_URL1="https://github.com/NVIDIA/egl-gbm/archive/refs/tags/${PKG_VER}/egl-gbm-${PKG_VER}.tar.gz"
PKG_TARBALL="egl-gbm-${PKG_VER}.tar.gz"
PKG_DIR="egl-gbm-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
