PKG_NAME="eglexternalplatform"
PKG_VER="1.2.1"
PKG_URL1="https://github.com/NVIDIA/eglexternalplatform/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="eglexternalplatform-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
