PKG_NAME="elfutils"
PKG_VER="0.196"
PKG_URL1="https://sourceware.org/elfutils/ftp/${PKG_VER}/elfutils-${PKG_VER}.tar.bz2"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --enable-libdebuginfod"
