PKG_NAME="ethtool"
PKG_VER="7.0"
PKG_URL1="https://mirrors.edge.kernel.org/pub/software/network/ethtool/ethtool-${PKG_VER}.tar.xz"
PKG_URL2="https://www.kernel.org/pub/software/network/ethtool/ethtool-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--prefix=/usr"
