PKG_NAME="expat"
PKG_VER="2.7.4"
PKG_URL1="https://github.com/libexpat/libexpat/releases/download/R_2_7_4/expat-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --docdir=/usr/share/doc/expat-${PKG_VER}"
PKG_POST_INSTALL="install -v -m644 doc/*.{html,css} /usr/share/doc/expat-${PKG_VER}"
