PKG_NAME="expect"
PKG_VER="5.45.4"
PKG_URL1="https://sourceforge.net/projects/expect/files/Expect/${PKG_VER}/expect${PKG_VER}.tar.gz"
PKG_TARBALL="expect${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="curl -sL https://www.linuxfromscratch.org/patches/lfs/development/expect-5.45.4-gcc15-1.patch | patch -Np1"
PKG_OPTS="--with-tcl=/usr/lib --with-tclinclude=/usr/include"
