PKG_NAME="extra-cmake-modules"
PKG_VER="6.28.0"
PKG_URL1="https://download.kde.org/stable/frameworks/${PKG_VER%.*}/extra-cmake-modules-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTING=OFF"
