PKG_NAME="fail2ban"
PKG_VER="1.1.1"
PKG_URL1="https://github.com/fail2ban/fail2ban/archive/refs/tags/${PKG_VER}/fail2ban-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="python3 setup.py build"
PKG_CUSTOM_INSTALL="python3 setup.py install --prefix=/usr"
