PKG_NAME="fdk-aac"
PKG_VER="2.0.3"
PKG_URL1="https://github.com/mstorsjo/fdk-aac/archive/v${PKG_VER}.tar.gz"
PKG_TARBALL="fdk-aac-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="autoreconf -fiv"
PKG_OPTS="--disable-static"
