PKG_NAME="ffmpeg"
PKG_VER="8.1.1"
PKG_URL1="https://ffmpeg.org/releases/ffmpeg-${PKG_VER}.tar.xz"
PKG_TARBALL="ffmpeg-${PKG_VER}.tar.xz"
PKG_DIR="ffmpeg-${PKG_VER}"
PKG_OPTS="--enable-shared \
    --disable-static \
    --enable-gpl \
    --enable-nonfree \
    --enable-libass \
    --enable-libdav1d \
    --enable-libfreetype \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libsvtav1 \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-openssl \
    --enable-vaapi \
    --enable-libdrm"
