PKG_NAME="ffmpegthumbnailer"
PKG_VER="2.3.0"
PKG_URL1="https://github.com/dirkvdb/ffmpegthumbnailer/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="ffmpegthumbnailer-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DENABLE_GIO=ON -DENABLE_THUMBNAILER=ON -DCMAKE_INSTALL_LIBDIR=lib"
PKG_POST_INSTALL="rm -f /usr/lib64/libffmpegthumbnailer.so /usr/lib64/libffmpegthumbnailer.so.4 /usr/lib64/libffmpegthumbnailer.so.4.16.1 && ldconfig"
