PKG_NAME="firefox"
PKG_VER="151.0.4"
PKG_BUILD_TYPE="custom"
PKG_URL1="https://ftp.mozilla.org/pub/firefox/releases/${PKG_VER}/linux-x86_64/en-US/firefox-${PKG_VER}.tar.xz"
PKG_URL2="https://download-installer.cdn.mozilla.net/pub/firefox/releases/${PKG_VER}/linux-x86_64/en-US/firefox-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_TARBALL="firefox-${PKG_VER}.tar.xz"
PKG_OPTS=""
PKG_CASCADE_SKIP="prebuilt binary — skip cascade"
PKG_STRIP_COMPONENTS="0"
PKG_CUSTOM_BUILD="
    echo '[STEP] Firefox is pre-compiled. Skipping compilation...'
"

PKG_CUSTOM_INSTALL="
    echo '[STEP] Installing pre-compiled Firefox binaries...'
    rm -rf /opt/firefox
    mkdir -p /opt/firefox
    cp -Rp firefox/* /opt/firefox/
    mkdir -p /usr/bin
    ln -sf /opt/firefox/firefox /usr/bin/firefox
"
