PKG_NAME="flac"
PKG_VER="1.5.0"
PKG_URL1="https://github.com/xiph/flac/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="flac-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF -DINSTALL_MANPAGES=OFF -DWITH_FORTIFY_SOURCE=OFF"
