PKG_NAME="flatpak"
PKG_VER="1.16.6"
PKG_URL1="https://github.com/flatpak/flatpak/releases/download/${PKG_VER}/flatpak-${PKG_VER}.tar.xz"
PKG_TARBALL="flatpak-${PKG_VER}.tar.xz"
PKG_DIR="flatpak-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Ddocbook_docs=disabled \
    -Dgtkdoc=disabled \
    -Dman=disabled \
    -Dtests=false \
    -Dhttp_backend=curl \
    -Dsandboxed_triggers=false"
