PKG_NAME="flex"
PKG_VER="2.6.4"
PKG_URL1="https://github.com/westes/flex/releases/download/v${PKG_VER}/flex-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --docdir=/usr/share/doc/flex-${PKG_VER}"
PKG_POST_INSTALL="ln -sfv flex /usr/bin/lex && ln -sfv flex.1 /usr/share/man/man1/lex.1"
