PKG_NAME="flit-core"
PKG_VER="4.0.0"
PKG_URL1="https://github.com/pypa/flit/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="flit-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_STRIP_COMPONENTS="2"
PKG_CUSTOM_BUILD="pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps \$PWD"
PKG_CUSTOM_INSTALL="pip3 install --no-index --find-links dist --force-reinstall --no-deps flit_core"
