PKG_NAME="fontconfig"
PKG_VER="2.18.1"
PKG_URL1="https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/${PKG_VER}/fontconfig-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="2300f3dbfa7253b3a44f4feecdbc8dfa45dde5dc2cfb71fceaf31f394cb41031"
