PKG_NAME="fontconfig"
PKG_VER="2.18.2"
PKG_URL1="https://gitlab.freedesktop.org/api/v4/projects/890/packages/generic/fontconfig/${PKG_VER}/fontconfig-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
