PKG_NAME="fuse"
PKG_VER="3.18.2"
PKG_URL1="https://github.com/libfuse/libfuse/releases/download/fuse-${PKG_VER}/fuse-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Duseroot=false -Dtests=false"
