PKG_NAME="fzf"
PKG_VER="0.74.1"
PKG_URL1="https://github.com/junegunn/fzf/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="fzf-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="go build -o fzf ."
PKG_CUSTOM_INSTALL="install -m755 fzf /usr/local/bin/fzf"
