PKG_NAME="gawk"
PKG_VER="5.4.0"
PKG_URL1="https://ftp.gnu.org/gnu/gawk/gawk-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="sed -i 's/extras//' Makefile.in"
PKG_OPTS=""
PKG_POST_INSTALL="rm -f /usr/bin/gawk-${PKG_VER} && ln -sfv gawk.1 /usr/share/man/man1/awk.1"
