PKG_NAME="gdbm"
PKG_VER="1.26"
PKG_URL1="https://ftpmirror.gnu.org/gdbm/gdbm-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --enable-libgdbm-compat --docdir=/usr/share/doc/gdbm-${PKG_VER}"
PKG_POST_INSTALL="make -C doc install-html docdir=/usr/share/doc/gdbm-${PKG_VER}"
