PKG_NAME="gdk-pixbuf"
PKG_VER="2.44.6"
PKG_URL1="https://download.gnome.org/sources/gdk-pixbuf/${PKG_VER%.*}/gdk-pixbuf-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dinstalled_tests=false -Dman=false -Ddocumentation=false -Dintrospection=enabled -Dpng=enabled -Dtiff=enabled -Djpeg=enabled -Dglycin=disabled"
