PKG_NAME="gettext"
PKG_VER="1.0"
PKG_URL1="https://ftpmirror.gnu.org/gettext/gettext-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_OPTS="--disable-static --docdir=/usr/share/doc/gettext-${PKG_VER}"
PKG_POST_INSTALL="chmod -v 0755 /usr/lib/preloadable_libintl.so"
