PKG_NAME="girara"
PKG_VER="2026.02.04"
PKG_URL1="https://github.com/pwmt/girara/archive/${PKG_VER}/girara-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled"
