PKG_NAME="git"
PKG_VER="2.55.0"
PKG_URL1="https://www.kernel.org/pub/software/scm/git/git-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--with-openssl --with-curl --with-libpcre2 --with-python=/usr/bin/python3"
