PKG_NAME="glaze"
PKG_VER="7.7.1"
PKG_URL1="https://github.com/stephenberry/glaze/archive/refs/tags/v${PKG_VER}/glaze-${PKG_VER}.tar.gz"
PKG_TARBALL="glaze-${PKG_VER}.tar.gz"
PKG_DIR="glaze-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTING=OFF"
