PKG_NAME="glib"
PKG_VER="2.88.1"
PKG_URL1="https://download.gnome.org/sources/glib/2.88/glib-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/glib-${PKG_VER}.tar.xz"
PKG_TARBALL="glib-${PKG_VER}.tar.xz"
PKG_DIR="glib-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false \
    -Dintrospection=enabled \
    -Ddocumentation=false"
PKG_SHA256="51ab804c56f6eab3e5045c774d1290ac5e4c923d4f9a3d8e33123bee45c1840e"
