PKG_NAME="glib-networking"
PKG_VER="2.80.1"
PKG_URL1="https://download.gnome.org/sources/glib-networking/${PKG_VER%.*}/glib-networking-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dlibproxy=disabled"
PKG_SHA256="b80e2874157cd55071f1b6710fa0b911d5ac5de106a9ee2a4c9c7bee61782f8e"
