PKG_NAME="glm"
PKG_VER="1.0.3"
PKG_URL1="https://github.com/g-truc/glm/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/glm /usr/share/glm /usr/lib64/libglm.a"
PKG_SHA256="6775e47231a446fd086d660ecc18bcd076531cfedd912fbd66e576b118607001"
