PKG_NAME="glslang"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/glslang/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="glslang-${PKG_VER}.tar.gz"
PKG_DIR="glslang-vulkan-sdk-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/glslang /usr/lib64/cmake/glslang /usr/lib64/libSPIRV.so* /usr/lib64/libglslang*.so* /usr/bin/glslang /usr/bin/glslangValidator"
PKG_CMAKE_OPTS="-DBUILD_SHARED_LIBS=ON -DGLSLANG_TESTS=OFF -DENABLE_OPT=OFF"
