PKG_NAME="gnupg"
PKG_VER="2.5.18"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/gnupg/gnupg-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--docdir=/usr/share/doc/gnupg-${PKG_VER} --disable-rpath"
PKG_SHA256="0dbd64e0322fe1a4813360d46539d5f8daf4a8fa235cf5fce464e8b0214a7e4f"
