PKG_NAME="gnutls"
PKG_VER="3.8.13"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/gnutls/v3.8/gnutls-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--docdir=/usr/share/doc/gnutls-${PKG_VER} --with-default-trust-store-pkcs11=pkcs11: --disable-static"
PKG_POST_INSTALL="ln -sf /etc/pki/tls/certs/ca-bundle.crt /etc/ssl/ca-bundle.crt"
PKG_SHA256="ffed8ec1bf09c2426d4f14aae377de4753b53e537d685e604e99a8b16ca9c97e"
