PKG_NAME="go"
PKG_VER="1.26.4"
PKG_URL1="https://go.dev/dl/go${PKG_VER}.linux-amd64.tar.gz"
PKG_URL2="https://dl.google.com/go/go${PKG_VER}.linux-amd64.tar.gz"
PKG_URL3="https://mirrors.aliyun.com/golang/go${PKG_VER}.linux-amd64.tar.gz"
PKG_TARBALL="go${PKG_VER}.linux-amd64.tar.gz"
PKG_DIR="go"
PKG_PREFIX="/usr/local"
PKG_STRIP_COMPONENTS="0"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="rm -rf /usr/local/go && cp -r go /usr/local/"
