PKG_NAME="gobject-introspection"
PKG_VER="1.86.0"
PKG_URL1="https://download.gnome.org/sources/gobject-introspection/${PKG_VER%.*}/gobject-introspection-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
