PKG_NAME="gobject-introspection"
PKG_VER="1.86.0"
PKG_URL1="https://download.gnome.org/sources/gobject-introspection/${PKG_VER%.*}/gobject-introspection-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="920d1a3fcedeadc32acff95c2e203b319039dd4b4a08dd1a2dfd283d19c0b9ae"
