PKG_NAME="gperf"
PKG_VER="3.3"
PKG_URL1="https://ftpmirror.gnu.org/gperf/gperf-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_OPTS="--docdir=/usr/share/doc/gperf-${PKG_VER}"
