PKG_NAME="gperf"
PKG_VER="3.3"
PKG_URL1="https://ftpmirror.gnu.org/gperf/gperf-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_OPTS="--docdir=/usr/share/doc/gperf-${PKG_VER}"
PKG_SHA256="fd87e0aba7e43ae054837afd6cd4db03a3f2693deb3619085e6ed9d8d9604ad8"
