PKG_NAME="gpgme"
PKG_VER="2.1.0"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/gpgme/gpgme-${PKG_VER}.tar.bz2"
PKG_TARBALL="gpgme-${PKG_VER}.tar.bz2"
PKG_DIR="gpgme-${PKG_VER}"
PKG_OPTS=""
PKG_SHA256="841c5ea53fc26259f4fbf0e8bde982dea1b8a1ca0cb77e681c82b050566bf92b"
