PKG_NAME="graphene"
PKG_VER="1.10.8"
PKG_URL1="https://download.gnome.org/sources/graphene/${PKG_VER%.*}/graphene-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dintrospection=enabled -Dgtk_doc=false"
