PKG_NAME="graphviz"
PKG_VER="14.1.5"
PKG_URL1="https://gitlab.com/graphviz/graphviz/-/archive/${PKG_VER}/graphviz-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --without-qt --without-java --without-perl --without-python --without-ruby --without-tcl"
