PKG_NAME="grep"
PKG_VER="3.12"
PKG_URL1="https://ftpmirror.gnu.org/grep/grep-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="sed -i 's/echo/#echo/' src/egrep.sh"
PKG_OPTS=""
PKG_SHA256="2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9"
