PKG_NAME="grim"
PKG_VER="1.5.0"
PKG_URL1="https://gitlab.freedesktop.org/emersion/grim/-/archive/v${PKG_VER}/grim-v${PKG_VER}.tar.gz"
PKG_TARBALL="grim-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
