PKG_NAME="groff"
PKG_VER="1.24.1"
PKG_URL1="https://ftp.gnu.org/gnu/groff/groff-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="PAGE=A4 ./configure --prefix=/usr && make"
PKG_CUSTOM_INSTALL="make install"
PKG_SHA256="74e2819795b6aff431aeac983d63a9c8968eeaba2a2eba7df8ba4c7b41e7cfd8"
