PKG_NAME="groff"
PKG_VER="1.23.0"
PKG_URL1="https://ftpmirror.gnu.org/groff/groff-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="PAGE=A4 ./configure --prefix=/usr && make"
PKG_CUSTOM_INSTALL="make install"
