PKG_NAME="grub"
PKG_VER="2.14"
PKG_URL1="https://ftpmirror.gnu.org/grub/grub-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="unset CFLAGS CPPFLAGS CXXFLAGS LDFLAGS"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --sysconfdir=/etc --disable-efiemu --with-platform=efi --target=x86_64 --disable-werror && make"
PKG_CUSTOM_INSTALL="make install && mv -v /etc/bash_completion.d/grub /usr/share/bash-completion/completions && install -vm755 grub-mkfont /usr/bin/"
