PKG_NAME="gst-plugins-base"
PKG_VER="1.28.3"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-plugins-base/gst-plugins-base-${PKG_VER}.tar.xz"
PKG_TARBALL="gst-plugins-base-${PKG_VER}.tar.xz"
PKG_DIR="gst-plugins-base-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dexamples=disabled \
    -Dintrospection=enabled"
