PKG_NAME="gst-plugins-good"
PKG_VER="1.28.4"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dexamples=disabled -Dqt5=disabled -Dqt6=disabled"
