PKG_NAME="gst-plugins-ugly"
PKG_VER="1.28.4"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled"
PKG_SHA256="5486cd145c5af43259fd37caca59d048e2a67ddb07082ea8f50ef0f02a85f8a5"
