PKG_NAME="gst-libav"
PKG_VER="1.28.5"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled"
