PKG_NAME="gst-plugins-bad"
PKG_VER="1.28.3"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-plugins-bad/gst-plugins-bad-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/gst-plugins-bad-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_MESON_OPTS="-Dintrospection=disabled \
  -Dexamples=disabled \
  -Dtests=disabled \
  -Ddoc=disabled"
PKG_PRE_BUILD="
    [ -L /usr/lib64/libvulkan.so ] || \
        ln -sf /usr/lib64/libvulkan.so.1.4.350 /usr/lib64/libvulkan.so
"
