PKG_NAME="gst-plugins-good"
PKG_VER="1.28.4"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-plugins-good/gst-plugins-good-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dexamples=disabled -Dqt5=disabled -Dqt6=disabled"
PKG_SHA256="c825ea737c59cea0e4a0c41da2388045ff5dd32d162220ac93a7a82ee4a04e61"
