PKG_NAME="gst-libav"
PKG_VER="1.28.4"
PKG_URL1="https://gstreamer.freedesktop.org/src/gst-libav/gst-libav-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled"
PKG_SHA256="bd17a5df2874a7a58bcbaf7b940223379ad9613624db8ead783db03e74bb904b"
