PKG_NAME="gtk"
PKG_VER="3.24.52"
PKG_URL1="https://download.gnome.org/sources/gtk+/3.24/gtk+-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/gtk+-${PKG_VER}.tar.xz"
PKG_URL3="https://ftp.acc.umu.se/pub/GNOME/sources/gtk+/3.24/gtk+-${PKG_VER}.tar.xz"
PKG_TARBALL="gtk-${PKG_VER}.tar.xz"
PKG_DIR="gtk-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dman=false -Dbroadway_backend=true"
PKG_SHA256="80931fa472a77b9a164f6740e3c0b444fac6770054632d35a7ff9d679e5e7b9f"
