PKG_NAME="gtk4"
PKG_VER="4.22.4"
PKG_URL1="https://download.gnome.org/sources/gtk/4.22/gtk-${PKG_VER}.tar.xz"
PKG_TARBALL="gtk-${PKG_VER}.tar.xz"
PKG_DIR="gtk-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dmedia-gstreamer=enabled \
    -Dbuild-tests=false \
    -Dbuild-examples=false \
    -Dintrospection=enabled"
PKG_SHA256="51bd9f60c7d23a665a556c7364c21fb2e4e282566b3e7e092455e8f910330893"
