PKG_NAME="gzip"
PKG_VER="1.14"
PKG_URL1="https://ftpmirror.gnu.org/gzip/gzip-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_SHA256="01a7b881bd220bfdf615f97b8718f80bdfd3f6add385b993dcf6efd14e8c0ac6"
