PKG_NAME="hardinfo2"
PKG_VER="2.2.16"
PKG_URL1="https://github.com/hardinfo2/hardinfo2/archive/refs/tags/release-${PKG_VER}/hardinfo2-release-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_PREFIX=/usr"
PKG_SRC_DIR="hardinfo2-release-${PKG_VER}"
