PKG_NAME="harfbuzz"
PKG_VER="14.2.1"
PKG_URL1="https://github.com/harfbuzz/harfbuzz/releases/download/${PKG_VER}/harfbuzz-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
