PKG_NAME="htop"
PKG_VER="3.5.2"
PKG_URL1="https://github.com/htop-dev/htop/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS="--disable-unicode --disable-unicode-wide --without-ncursesw --enable-linux-affinity"
