PKG_NAME="hyprgraphics"
PKG_VER="0.5.1"
PKG_URL1="https://github.com/hyprwm/hyprgraphics/archive/refs/tags/v${PKG_VER}/hyprgraphics-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr"
