PKG_NAME="hyprland"
PKG_VER="0.54.3"
PKG_URL1="https://github.com/hyprwm/Hyprland/archive/refs/tags/v${PKG_VER}/hyprland-${PKG_VER}.tar.gz"
PKG_TARBALL="hyprland-${PKG_VER}.tar.gz"
PKG_DIR="Hyprland-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="git init && git add -A && git commit -m 'v${PKG_VER}' && git tag v${PKG_VER}"
PKG_CMAKE_OPTS="-DCMAKE_BUILD_TYPE=Release \
    -DBUILD_TESTING=OFF"
PKG_MANUAL_CASCADE="hyprland-guiutils xdg-desktop-portal-hyprland"
