PKG_NAME="hyprland-guiutils"
PKG_VER="0.2.1"
PKG_URL1="https://github.com/hyprwm/hyprland-guiutils/archive/refs/tags/v${PKG_VER}/hyprland-guiutils-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS=""
PKG_SHA256="8de6ab7295dd120bab6b6b3e884b27b3c6ccc38ae345f3144bf9b5ad79251bcb"
