PKG_NAME="hyprwayland-scanner"
PKG_VER="0.4.6"
PKG_URL1="https://github.com/hyprwm/hyprwayland-scanner/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="git init && git commit --allow-empty -m 'init' && git tag v${PKG_VER}"
PKG_SHA256="05f55fd1a20d8ca81b5030980fdb7c87147749230145bdb3745af2741d617f5c"
