PKG_NAME="hyprwire"
PKG_VER="0.3.1"
PKG_URL1="https://github.com/hyprwm/hyprwire/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="git init && git commit --allow-empty -m 'init' && git tag v${PKG_VER}"
PKG_POST_INSTALL="ln -sf libhyprwire.so.0.3.1 /usr/lib64/libhyprwire.so.3 && ln -sf libhyprwire.so.3 /usr/lib64/libhyprwire.so"
