PKG_NAME="hyprlock"
PKG_VER="0.9.5"
PKG_URL1="https://github.com/hyprwm/hyprlock/archive/refs/tags/v${PKG_VER}/hyprlock-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTING=OFF"
PKG_POST_INSTALL="cp /etc/pam.d/hyprlock.bak /etc/pam.d/hyprlock && chmod u+s /usr/bin/hyprlock"
PKG_SHA256="cbc49fc5553c550131e1a15089847501de42579944814229bfa9f8ea18519f89"
