PKG_NAME="hyprutils"
PKG_VER="0.13.1"
PKG_URL1="https://github.com/hyprwm/hyprutils/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="git init && git commit --allow-empty -m 'init' && git tag v${PKG_VER}"
PKG_POST_INSTALL="ln -sf libhyprutils.so.0.13.0 /usr/lib64/libhyprutils.so.12 && ln -sf libhyprutils.so.12 /usr/lib64/libhyprutils.so"
PKG_MANUAL_CASCADE="ironbar mpv swayimg libinput luajit"
