PKG_NAME="iana-etc"
PKG_VER="20260529"
PKG_URL1="https://github.com/Mic92/iana-etc/releases/download/${PKG_VER}/iana-etc-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="cp -v services protocols /etc"
