PKG_NAME="iana-etc"
PKG_VER="20260529"
PKG_URL1="https://github.com/Mic92/iana-etc/releases/download/${PKG_VER}/iana-etc-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="cp -v services protocols /etc"
PKG_SHA256="4100d8c4e8653701972e68f8326be75ecb0aa08b374e57553b0d114c6b7acdf8"
