PKG_NAME="imagemagick"
PKG_VER="7.1.2.25"
PKG_URL1="https://download.imagemagick.org/archive/ImageMagick-${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_URL2="https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_URL3=""
PKG_TARBALL="ImageMagick-${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_OPTS="--sysconfdir=/etc \
  --enable-hdri \
  --with-modules \
  --with-gslib \
  --with-webp \
  --with-xml \
  --disable-static"
PKG_SHA256="c4ce2d982fbedf0347aeca804326308311d767c8da6a69e91ed39371f8de137b"
