PKG_NAME="imagemagick"
PKG_VER="7.1.2.26"
PKG_URL1="https://download.imagemagick.org/archive/ImageMagick-${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_URL2="https://github.com/ImageMagick/ImageMagick/archive/refs/tags/${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_URL3=""
PKG_TARBALL="ImageMagick-${PKG_VER%.*}-${PKG_VER##*.}.tar.gz"
PKG_OPTS="--sysconfdir=/etc \
  --enable-hdri \
  --with-modules \
  --with-gslib \
  --with-webp \
  --with-xml \
  --disable-static"
