PKG_NAME="inetutils"
PKG_VER="2.8"
PKG_URL1="https://ftpmirror.gnu.org/inetutils/inetutils-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="sed -i 's/def HAVE_TERMCAP_TGETENT/ 1/' telnet/telnet.c"
PKG_OPTS="--bindir=/usr/bin --localstatedir=/var --disable-logger --disable-whois --disable-rcp --disable-rexec --disable-rlogin --disable-rsh --disable-servers"
PKG_POST_INSTALL="mv -v /usr/{,s}bin/ifconfig"
PKG_SHA256="57b3cf4f77555992881e5ba2a09a63b05aa2c56342a60ed4305b5f45938390b5"
