PKG_NAME="iniparser"
PKG_VER="4.2.6"
PKG_URL1="https://github.com/ndevilla/iniparser/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_POST_INSTALL="ln -sf libiniparser.so.4.2.6 /usr/lib64/libiniparser.so.4 && ln -sf libiniparser.so.4 /usr/lib64/libiniparser.so"
PKG_SHA256="a0bd370713a744b1fa8ec27bba889ebf9dbd43060ec92e07fbe91fb43e3cb3ac"
