PKG_NAME="intltool"
PKG_VER="0.51.0"
PKG_URL1="https://launchpad.net/intltool/trunk/0.51.0/+download/intltool-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="sed -i 's:\\\\\${:\\\\\$\\\\{:' intltool-update.in"
PKG_OPTS=""
PKG_POST_INSTALL="install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-${PKG_VER}/I18N-HOWTO"
