PKG_NAME="iproute2"
PKG_VER="7.0.0"
PKG_URL1="https://mirrors.edge.kernel.org/pub/linux/utils/net/iproute2/iproute2-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="sed -i /ARPD/d Makefile && rm -fv man/man8/arpd.8"
PKG_CUSTOM_BUILD="make NETNS_RUN_DIR=/run/netns"
PKG_CUSTOM_INSTALL="make SBINDIR=/usr/sbin install"
PKG_SHA256="e62890f7b5de63c05a3bf331dc8deb4c015c336013f341a4edf46969797f2f4e"
