PKG_NAME="ironbar"
PKG_VER="0.19.0"
PKG_URL1="https://github.com/JakeStanger/ironbar/archive/refs/tags/v${PKG_VER}/ironbar-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -Dm755 target/release/ironbar /usr/bin/ironbar"
