PKG_NAME="jansson"
PKG_VER="2.15.1"
PKG_URL1="https://github.com/akheron/jansson/releases/download/v${PKG_VER}/jansson-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -DJANSSON_BUILD_SHARED_LIBS=ON -DJANSSON_WITHOUT_TESTS=ON -DJANSSON_BUILD_DOCS=OFF"
PKG_PRE_BUILD="rm -rf /usr/lib/cmake/jansson /usr/include/jansson.h /usr/include/jansson_config.h"
