PKG_NAME="jq"
PKG_VER="1.8.2"
PKG_URL1="https://github.com/jqlang/jq/releases/download/jq-${PKG_VER}/jq-${PKG_VER}.tar.gz"
PKG_TARBALL="jq-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS="--with-oniguruma=builtin"
PKG_PRE_BUILD="rm -f /usr/lib/libonig.* /usr/include/oniggnu.h /usr/include/oniguruma.h /usr/bin/onig-config /usr/lib/pkgconfig/oniguruma.pc /usr/lib/libjq.* /usr/include/jq.h /usr/include/jv.h /usr/bin/jq /usr/lib/pkgconfig/libjq.pc"
