PKG_NAME="json-c"
PKG_VER="0.19"
PKG_URL1="https://codeload.github.com/json-c/json-c/tar.gz/refs/tags/json-c-${PKG_VER}-20260627"
PKG_TARBALL="json-c-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -DBUILD_TESTING=OFF"
PKG_PRE_BUILD="rm -rf /usr/lib/libjson-c* /usr/lib64/libjson-c* /usr/include/json-c /usr/lib/cmake/json-c /usr/lib64/cmake/json-c"
