PKG_NAME="kbd"
PKG_VER="2.10.0"
PKG_URL1="https://www.kernel.org/pub/linux/utils/kbd/kbd-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="patch -Np1 -i /sources/patches/kbd-${PKG_VER}-backspace-1.patch"
PKG_OPTS="--disable-vlock"
PKG_SHA256="6e5ca4f8d76ee9e3a8db700b667f13e12aac9933828a64e1aaad93d26be9b479"
