PKG_NAME="kbd"
PKG_VER="2.9.0"
PKG_URL1="https://www.kernel.org/pub/linux/utils/kbd/kbd-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="patch -Np1 -i /sources/patches/kbd-${PKG_VER}-backspace-1.patch && sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure && sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in"
PKG_OPTS="--disable-vlock"
