PKG_NAME="kitty"
PKG_VER="0.48.0"
PKG_URL1="https://github.com/kovidgoyal/kitty/releases/download/v${PKG_VER}/kitty-${PKG_VER}.tar.xz"
PKG_URL2="https://github.com/kovidgoyal/kitty/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="kitty-${PKG_VER}.tar.xz"
PKG_PREFIX="/usr/local"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make linux-package -j$(nproc)"
PKG_CUSTOM_INSTALL="install -Dm755 linux-package/bin/kitty linux-package/bin/kitten /usr/local/bin/ && cp -r linux-package/lib/kitty /usr/local/lib/ && cp -r linux-package/share/* /usr/local/share/"
