# /etc/bogartpkg/packages.d/lcms2.conf
PKG_NAME="lcms2"
PKG_VER="2.19.1"
PKG_URL1="https://github.com/mm2/Little-CMS/releases/download/lcms${PKG_VER}/lcms2-${PKG_VER}.tar.gz"
PKG_URL2="https://downloads.sourceforge.net/lcms/lcms2-${PKG_VER}.tar.gz"
PKG_URL3="https://mirrors.kernel.org/gentoo/distfiles/lcms2-${PKG_VER}.tar.gz"
PKG_OPTS="--disable-static"
PKG_SHA256="bfc54f7bab59fbc921012014a8032e4cba4abd46db47d46b76416a8c0b2815c8"
