PKG_NAME="less"
PKG_VER="704"
PKG_URL1="https://www.greenwoodsoftware.com/less/less-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--sysconfdir=/etc"
PKG_SHA256="20a0b0a2bb2525fa53c7eee9beb854b4c9cf172eabb209af7020743547bfe9fb"
