PKG_NAME="libarchive"
PKG_VER="3.8.8"
PKG_URL1="https://github.com/libarchive/libarchive/releases/download/v${PKG_VER}/libarchive-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DENABLE_WERROR=OFF -DCMAKE_INSTALL_LIBDIR=lib"
PKG_PRE_BUILD="rm -rf /usr/lib64/libarchive.so /usr/lib64/libarchive.so.13 /usr/include/archive.h /usr/include/archive_entry.h /usr/lib64/pkgconfig/libarchive.pc"
