PKG_NAME="libadwaita"
PKG_VER="1.9.2"
PKG_URL1="https://github.com/GNOME/libadwaita/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="libadwaita-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dexamples=false -Dvapi=false"
