PKG_NAME="libaom"
PKG_VER="3.14.1"
PKG_URL1="https://storage.googleapis.com/aom-releases/libaom-${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/AOMediaCodec/libaom/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="libaom-${PKG_VER}.tar.gz"
PKG_CMAKE_OPTS="-DBUILD_SHARED_LIBS=ON \
  -DENABLE_TESTS=OFF \
  -DENABLE_DOCS=OFF \
  -DENABLE_EXAMPLES=OFF"
PKG_SHA256="44bf90dbd23e734d50e70a8c41c285193922938bd0d3bc2ee56764d181d55ef5"
