PKG_NAME="libaio"
PKG_VER="0.3.113"
PKG_URL1="https://pagure.io/libaio/archive/libaio-${PKG_VER}/libaio-libaio-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make"
PKG_CUSTOM_INSTALL="make install"
