PKG_NAME="libassuan"
PKG_VER="3.0.2"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/libassuan/libassuan-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_SHA256="d2931cdad266e633510f9970e1a2f346055e351bb19f9b78912475b8074c36f6"
