PKG_NAME="libass"
PKG_VER="0.17.4"
PKG_URL1="https://github.com/libass/libass/releases/download/${PKG_VER}/libass-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS=""
