PKG_NAME="libcap-ng"
PKG_VER="0.9.5"
PKG_URL1="https://github.com/stevegrubb/libcap-ng/archive/refs/tags/v${PKG_VER}/libcap-ng-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="touch NEWS && autoreconf -fiv --warnings=none"
PKG_OPTS="--disable-static --without-python --without-python3"
