PKG_NAME="libcap"
PKG_VER="2.78"
PKG_URL1="https://www.kernel.org/pub/linux/libs/security/linux-privs/libcap2/libcap-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="sed -i '/install -m.*STA/d' libcap/Makefile"
PKG_CUSTOM_BUILD="make prefix=/usr lib=lib"
PKG_CUSTOM_INSTALL="make prefix=/usr lib=lib install"
