PKG_NAME="libdrm"
PKG_VER="2.4.134"
PKG_URL1="https://dri.freedesktop.org/libdrm/libdrm-${PKG_VER}.tar.xz"
PKG_URL2="https://gitlab.freedesktop.org/mesa/drm/-/archive/libdrm-${PKG_VER}/drm-libdrm-${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dudev=true -Dvalgrind=disabled"
PKG_SHA256="ac5e74d157830eb8bee44c6a6bf3ad49774ef0dd2a72bdad74a8f20308b52a95"
