PKG_NAME="libdecor"
PKG_VER="0.2.5"
PKG_URL1="https://gitlab.freedesktop.org/libdecor/libdecor/-/archive/${PKG_VER}/libdecor-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Ddemo=false -Dinstall_demo=false -Dgtk=enabled"
