PKG_NAME="libelf"
PKG_VER="0.195"
PKG_URL1="https://sourceware.org/ftp/elfutils/${PKG_VER}/elfutils-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_DIR="elfutils-${PKG_VER}"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --disable-debuginfod --enable-libdebuginfod=dummy && make -C lib && make -C libelf"
PKG_CUSTOM_INSTALL="make -C libelf install && install -vm644 config/libelf.pc /usr/lib/pkgconfig && rm /usr/lib/libelf.a"
PKG_SHA256="37629fdf7f1f3dc2818e138fca2b8094177d6c2d0f701d3bb650a561218dc026"
