PKG_NAME="libevdev"
PKG_VER="1.13.7"
PKG_URL1="https://www.freedesktop.org/software/libevdev/libevdev-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Ddocumentation=disabled"
