PKG_NAME="libffi"
PKG_VER="3.7.1"
PKG_URL1="https://github.com/libffi/libffi/releases/download/v${PKG_VER}/libffi-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --with-gcc-arch=native"
