PKG_NAME="libgudev"
PKG_VER="238"
PKG_URL1="https://download.gnome.org/sources/libgudev/${PKG_VER}/libgudev-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dintrospection=enabled -Dgtk_doc=false -Dvapi=disabled"
PKG_SHA256="61266ab1afc9d73dbc60a8b2af73e99d2fdff47d99544d085760e4fa667b5dd1"
