PKG_NAME="libgpg-error"
PKG_VER="1.61"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/libgpg-error/libgpg-error-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-install-gpg-error-config"
