PKG_NAME="libgudev"
PKG_VER="238"
PKG_URL1="https://download.gnome.org/sources/libgudev/${PKG_VER}/libgudev-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=disabled -Dintrospection=enabled -Dgtk_doc=false -Dvapi=disabled"
