PKG_NAME="libinput"
PKG_VER="1.31.3"
PKG_URL1="https://gitlab.freedesktop.org/libinput/libinput/-/archive/${PKG_VER}/libinput-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dlibwacom=false -Ddebug-gui=false -Dtests=false -Ddocumentation=false"
