PKG_NAME="libical"
PKG_VER="4.0.3"
PKG_URL1="https://github.com/libical/libical/releases/download/v${PKG_VER}/libical-${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/libical/libical/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="libical-${PKG_VER}.tar.gz"
PKG_CMAKE_OPTS="-DLIBICAL_GLIB=ON \
  -DLIBICAL_GLIB_BUILD_DOCS=False \
  -DLIBICAL_GLIB_VAPI=OFF \
  -DLIBICAL_GOBJECT_INTROSPECTION=False \
  -DLIBICAL_JAVA_BINDINGS=False \
  -DBUILD_SHARED_LIBS=ON"
