PKG_NAME="libjpeg-turbo"
PKG_VER="3.2.0"
PKG_URL1="https://github.com/libjpeg-turbo/libjpeg-turbo/releases/download/${PKG_VER}/libjpeg-turbo-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -DENABLE_STATIC=OFF"
PKG_PRE_BUILD="rm -rf /usr/lib/libjpeg* /usr/lib/libturbojpeg* /usr/include/jpeglib.h /usr/include/turbojpeg.h"
