PKG_NAME="libjxl"
PKG_VER="0.11.2"
PKG_URL1="https://github.com/libjxl/libjxl/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2="https://codeberg.org/libjxl/libjxl/archive/v${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="libjxl-${PKG_VER}.tar.gz"
PKG_CMAKE_OPTS="-DJPEGXL_ENABLE_BENCHMARK=ON \
  -DJPEGXL_ENABLE_EXAMPLES=ON \
  -DJPEGXL_ENABLE_TOOLS=ON \
  -DJPEGXL_ENABLE_OPENEXR=ON \
  -DJPEGXL_ENABLE_TRANSCODE_JPEG=ON \
  -DJPEGXL_ENABLE_BOXES=ON \
  -DJPEGXL_ENABLE_MANPAGES=OFF \
  -DJPEGXL_ENABLE_PLUGINS=OFF \
  -DJPEGXL_ENABLE_SJPEG=OFF \
  -DJPEGXL_ENABLE_SKCMS=OFF \
  -DJPEGXL_ENABLE_VIEWERS=OFF \
  -DJPEGXL_ENABLE_JPEGLI=OFF \
  -DJPEGXL_ENABLE_AVX512=OFF"
PKG_SHA256="ab38928f7f6248e2a98cc184956021acb927b16a0dee71b4d260dc040a4320ea"
