PKG_NAME="libksba"
PKG_VER="1.8.0"
PKG_URL1="https://www.gnupg.org/ftp/gcrypt/libksba/libksba-${PKG_VER}.tar.bz2"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/libksba-${PKG_VER}.tar.bz2"
PKG_URL3=""
PKG_OPTS="--disable-dependency-tracking"
