PKG_NAME="libliftoff"
PKG_VER="0.5.0"
PKG_URL1="https://gitlab.freedesktop.org/emersion/libliftoff/-/archive/v${PKG_VER}/libliftoff-v${PKG_VER}.tar.gz"
PKG_TARBALL="libliftoff-v${PKG_VER}.tar.gz"
PKG_DIR="libliftoff-v${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
