PKG_NAME="libnvme"
PKG_VER="1.16.2"
PKG_URL1="https://github.com/linux-nvme/libnvme/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="libnvme-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dopenssl=enabled"
