PKG_NAME="libnotify"
PKG_VER="0.8.8"
PKG_URL1="https://download.gnome.org/sources/libnotify/${PKG_VER%.*}/libnotify-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dintrospection=enabled -Dgtk_doc=false -Dman=false"
