PKG_NAME="libnotify"
PKG_VER="0.8.8"
PKG_URL1="https://download.gnome.org/sources/libnotify/${PKG_VER%.*}/libnotify-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dintrospection=enabled -Dgtk_doc=false -Dman=false"
PKG_SHA256="23420ef619dc2cb5aebad613f4823a2fa41c07e5a1d05628d40f6ec4b35bfddd"
