PKG_NAME="libpwquality"
PKG_VER="1.4.5"
PKG_URL1="https://github.com/libpwquality/libpwquality/releases/download/libpwquality-${PKG_VER}/libpwquality-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static --with-securedir=/usr/lib/security --disable-python-bindings"
PKG_SHA256="6fcf18b75d305d99d04d2e42982ed5b787a081af2842220ed63287a2d6a10988"
