PKG_NAME="libplacebo"
PKG_VER="7.360.1"
PKG_URL1="https://code.videolan.org/videolan/libplacebo/-/archive/v${PKG_VER}/libplacebo-v${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/haasn/libplacebo/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="libplacebo-${PKG_VER}.tar.gz"
PKG_MESON_OPTS="-Dvulkan=enabled -Dlcms=enabled -Dshaderc=enabled -Dopengl=enabled -Dglslang=disabled -Ddemos=false"
PKG_PRE_BUILD="
    [ -L /usr/lib64/libshaderc_shared.so ] || \
        ln -sf /usr/lib64/libshaderc_shared.so.1 /usr/lib64/libshaderc_shared.so
"
