PKG_NAME="libqb"
PKG_VER="2.0.10"
PKG_URL1="https://github.com/ClusterLabs/libqb/releases/download/v${PKG_VER}/libqb-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--prefix=/usr --sysconfdir=/etc --localstatedir=/var"
