PKG_NAME="librsvg"
PKG_VER="2.62.3"
PKG_URL1="https://download.gnome.org/sources/librsvg/2.62/librsvg-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/librsvg-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_MESON_OPTS="-Dintrospection=enabled \
  -Dpixbuf=enabled \
  -Dpixbuf-loader=enabled \
  -Dvala=disabled \
  -Ddocs=disabled \
  -Dtests=false"
PKG_POST_INSTALL="gdk-pixbuf-query-loaders --update-cache"
