PKG_NAME="libslirp"
PKG_VER="4.9.3"
PKG_URL1="https://gitlab.freedesktop.org/slirp/libslirp/-/archive/v${PKG_VER}/libslirp-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
