PKG_NAME="libsoup"
PKG_VER="3.6.6"
PKG_URL1="https://download.gnome.org/sources/libsoup/${PKG_VER%.*}/libsoup-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Ddocs=disabled -Dintrospection=disabled -Dvapi=disabled -Dsysprof=disabled"
PKG_SHA256="51ed0ae06f9d5a40f401ff459e2e5f652f9a510b7730e1359ee66d14d4872740"
