PKG_NAME="libseccomp"
PKG_VER="2.6.0"
PKG_URL1="https://github.com/seccomp/libseccomp/releases/download/v${PKG_VER}/libseccomp-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
