PKG_NAME="libtool"
PKG_VER="2.6.2"
PKG_URL1="https://ftp.gnu.org/gnu/libtool/libtool-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_POST_INSTALL="rm -fv /usr/lib/libltdl.a"
PKG_CASCADE_SKIP="held-git-version-gen-broken"
