PKG_NAME="libtiff"
PKG_VER="4.7.2"
PKG_URL1="https://download.osgeo.org/libtiff/tiff-${PKG_VER}.tar.xz"
PKG_TARBALL="tiff-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib -Dtiff-tests=OFF -Dtiff-docs=OFF"
PKG_PRE_BUILD="rm -rf /usr/lib/libtiff* /usr/lib64/libtiff* /usr/include/tiff*.h"
