PKG_NAME="libtool"
PKG_VER="2.6.1"
PKG_URL1="https://github.com/autotools-mirror/libtool/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="libtool-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="autoreconf -fiv"
PKG_OPTS=""
PKG_POST_INSTALL="rm -fv /usr/lib/libltdl.a"
