PKG_NAME="libtasn1"
PKG_VER="4.21.0"
PKG_URL1="https://ftp.gnu.org/gnu/libtasn1/libtasn1-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
PKG_SHA256="1d8a444a223cc5464240777346e125de51d8e6abf0b8bac742ac84609167dc87"
