PKG_NAME="libusb"
PKG_VER="1.0.30"
PKG_URL1="https://github.com/libusb/libusb/releases/download/v${PKG_VER}/libusb-${PKG_VER}.tar.bz2"
PKG_TARBALL="libusb-${PKG_VER}.tar.bz2"
PKG_DIR="libusb-${PKG_VER}"
PKG_OPTS="--disable-static"
PKG_SHA256="fea36f34f9156400209595e300840767ab1a385ede1dc7ee893015aea9c6dbaf"
