PKG_NAME="libvpx"
PKG_VER="1.17.0"
PKG_URL1="https://github.com/webmproject/libvpx/archive/refs/tags/v${PKG_VER}/libvpx-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --enable-shared --disable-static --enable-vp8 --enable-vp9 --enable-runtime-cpu-detect --enable-pic && make -j$(nproc)"
PKG_CUSTOM_INSTALL="make install"
