PKG_NAME="libva-utils"
PKG_VER="2.24.0"
PKG_URL1="https://github.com/intel/libva-utils/archive/refs/tags/${PKG_VER}/libva-utils-${PKG_VER}.tar.gz"
PKG_TARBALL="libva-utils-${PKG_VER}.tar.gz"
PKG_DIR="libva-utils-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
