PKG_NAME="libva"
PKG_VER="2.24.1"
PKG_URL1="https://github.com/intel/libva/archive/refs/tags/${PKG_VER}/libva-${PKG_VER}.tar.gz"
PKG_TARBALL="libva-${PKG_VER}.tar.gz"
PKG_DIR="libva-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
