PKG_NAME="libwebp"
PKG_VER="1.6.0"
PKG_URL1="https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-libwebpmux --enable-libwebpdemux --enable-libwebpdecoder --enable-libwebpextras --disable-static"
PKG_SHA256="e4ab7009bf0629fd11982d4c2aa83964cf244cffba7347ecd39019a9e38c4564"
