PKG_NAME="libxml2"
PKG_VER="2.15.3"
PKG_URL1="https://download.gnome.org/sources/libxml2/${PKG_VER%.*}/libxml2-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dpython=enabled -Ddocs=disabled"
PKG_SHA256="78262a6e7ac170d6528ebfe2efccdf220191a5af6a6cd61ea4a9a9a5042c7a07"
