PKG_NAME="libxcrypt"
PKG_VER="4.5.2"
PKG_URL1="https://github.com/besser82/libxcrypt/releases/download/v${PKG_VER}/libxcrypt-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="sed -i '/strchr/s/const//' lib/crypt-{sm3,gost}-yescrypt.c"
PKG_CONFIGURE_OPTS="--enable-hashes=strong,glibc --enable-obsolete-api=no --disable-static --disable-failure-tokens"
PKG_SHA256="71513a31c01a428bccd5367a32fd95f115d6dac50fb5b60c779d5c7942aec071"
