PKG_NAME="libxkbcommon"
PKG_VER="1.13.2"
PKG_URL1="https://github.com/xkbcommon/libxkbcommon/archive/refs/tags/xkbcommon-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_PRE_BUILD="rm -rf /usr/include/xkbcommon /usr/lib64/libxkbcommon* /usr/lib64/libxkbregistry* /usr/bin/xkbcli"
