PKG_NAME="libxft"
PKG_VER="2.3.9"
PKG_URL1="https://xorg.freedesktop.org/releases/individual/lib/libXft-${PKG_VER}.tar.xz"
PKG_TARBALL="libXft-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
