PKG_NAME="libxfont2"
PKG_VER="2.0.8"
PKG_URL1="https://xorg.freedesktop.org/releases/individual/lib/libXfont2-${PKG_VER}.tar.xz"
PKG_TARBALL="libXfont2-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
