PKG_NAME="libxinerama"
PKG_VER="1.1.6"
PKG_URL1="https://xorg.freedesktop.org/archive/individual/lib/libXinerama-${PKG_VER}.tar.xz"
PKG_TARBALL="libXinerama-${PKG_VER}.tar.xz"
PKG_DIR="libXinerama-${PKG_VER}"
PKG_OPTS="--disable-static"
PKG_SHA256="d00fc1599c303dc5cbc122b8068bdc7405d6fcb19060f4597fc51bd3a8be51d7"
