PKG_NAME="libxinerama"
PKG_VER="1.1.6"
PKG_URL1="https://xorg.freedesktop.org/archive/individual/lib/libXinerama-${PKG_VER}.tar.xz"
PKG_TARBALL="libXinerama-${PKG_VER}.tar.xz"
PKG_DIR="libXinerama-${PKG_VER}"
PKG_OPTS="--disable-static"
