PKG_NAME="libxtst"
PKG_VER="1.2.5"
PKG_URL1="https://xorg.freedesktop.org/archive/individual/lib/libXtst-${PKG_VER}.tar.xz"
PKG_TARBALL="libXtst-${PKG_VER}.tar.xz"
PKG_DIR="libXtst-${PKG_VER}"
PKG_OPTS="--disable-static"
PKG_SHA256="b50d4c25b97009a744706c1039c598f4d8e64910c9fde381994e1cae235d9242"
