PKG_NAME="linux-firmware"
PKG_VER="20260519"
PKG_URL1="https://mirrors.edge.kernel.org/pub/linux/kernel/firmware/linux-firmware-${PKG_VER}.tar.xz"
PKG_URL2="https://cdn.kernel.org/pub/linux/kernel/firmware/linux-firmware-${PKG_VER}.tar.xz"
PKG_TARBALL="linux-firmware-${PKG_VER}.tar.xz"
PKG_DIR="linux-firmware-${PKG_VER}"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="make install"
PKG_PRE_BUILD="sed -i 's/-j\$(NUM_JOBS)//' Makefile"
PKG_SHA256="b14e7197a290a7e5569f5ef790cde289bddc47e32126f2eb262a8e677fc39727"
