PKG_NAME="linux-pam"
PKG_VER="1.7.2"
PKG_URL1="https://github.com/linux-pam/linux-pam/releases/download/v${PKG_VER}/Linux-PAM-${PKG_VER}.tar.xz"
PKG_TARBALL="Linux-PAM-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Ddocdir=/usr/share/doc/Linux-PAM-${PKG_VER}"
PKG_POST_INSTALL="chmod -v 4755 /usr/sbin/unix_chkpwd"
