PKG_NAME="llvm"
PKG_VER="22.1.8"
PKG_URL1="https://github.com/llvm/llvm-project/releases/download/llvmorg-${PKG_VER}/llvm-project-${PKG_VER}.src.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_DIR="llvm-project-${PKG_VER}.src"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="mkdir -p build && cd build && cmake ../llvm \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr/local \
  -DLLVM_ENABLE_PROJECTS='clang;lld' \
  -DLLVM_TARGETS_TO_BUILD='X86;AMDGPU;NVPTX' \
  -DLLVM_BUILD_LLVM_DYLIB=ON \
  -DLLVM_LINK_LLVM_DYLIB=ON \
  -DCLANG_LINK_CLANG_DYLIB=ON \
  -DLLVM_INSTALL_UTILS=ON \
  -DBUILD_SHARED_LIBS=OFF && make -j\$(nproc)"
PKG_CUSTOM_INSTALL="cd build && make install"
