PKG_NAME="lua"
PKG_VER="5.5.0"
PKG_URL1="https://www.lua.org/ftp/lua-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make -j$(nproc) INSTALL_TOP=/usr linux"
PKG_CUSTOM_INSTALL="make INSTALL_TOP=/usr install"
PKG_MANUAL_CASCADE="ironbar mpv swayimg libinput luajit"
PKG_SHA256="57ccc32bbbd005cab75bcc52444052535af691789dba2b9016d5c50640d68b3d"
