PKG_NAME="luajit"
PKG_VER="2.1"
PKG_URL1="https://github.com/LuaJIT/LuaJIT/archive/refs/heads/v2.1/luajit-2.1.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make -j$(nproc) PREFIX=/usr"
PKG_CUSTOM_INSTALL="make install PREFIX=/usr"
PKG_SHA256="1d11c000dbd426a008c022d9aaf472288f3ded616f4088a922a2530600be6f33"
