PKG_NAME="lvm2"
PKG_VER="2.03.41"
PKG_URL1="https://sourceware.org/ftp/lvm2/LVM2.${PKG_VER}.tgz"
PKG_TARBALL="LVM2.${PKG_VER}.tgz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-cmdlib --enable-pkgconfig --enable-udev_sync --with-systemdsystemunitdir=/usr/lib/systemd/system"
