PKG_NAME="lynis"
PKG_VER="3.1.7"
PKG_URL1="https://github.com/CISOfy/lynis/archive/refs/tags/${PKG_VER}/lynis-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="echo 'no build needed'"
PKG_CUSTOM_INSTALL="rm -rf /opt/lynis && mkdir -p /opt/lynis && cp -r * /opt/lynis && ln -sf /opt/lynis/lynis /usr/bin/lynis"
