PKG_NAME="lz4"
PKG_VER="1.10.0"
PKG_URL1="https://github.com/lz4/lz4/releases/download/v${PKG_VER}/lz4-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make BUILD_STATIC=no PREFIX=/usr"
PKG_CUSTOM_INSTALL="make BUILD_STATIC=no PREFIX=/usr install"
PKG_SHA256="537512904744b35e232912055ccf8ec66d768639ff3abe5788d90d792ec5f48b"
