PKG_NAME="make"
PKG_VER="4.4.1"
PKG_URL1="https://ftpmirror.gnu.org/make/make-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_SHA256="dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3"
