PKG_NAME="mako"
PKG_VER="1.11.0"
PKG_URL1="https://github.com/emersion/mako/archive/refs/tags/v${PKG_VER}/mako-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dsd-bus-provider=libsystemd -Dicons=disabled"
