PKG_NAME="man-db"
PKG_VER="2.13.1"
PKG_URL1="https://download.savannah.gnu.org/releases/man-db/man-db-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--docdir=/usr/share/doc/man-db-${PKG_VER} --sysconfdir=/etc --disable-setuid --enable-cache-owner=bin --with-browser=/usr/bin/lynx --with-vgrind=/usr/bin/vgrind --with-grap=/usr/bin/grap"
PKG_SHA256="8afebb6f7eb6bb8542929458841f5c7e6f240e30c86358c1fbcefbea076c87d9"
