PKG_NAME="man-pages"
PKG_VER="6.18"
PKG_URL1="https://www.kernel.org/pub/linux/docs/man-pages/man-pages-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="rm -f man3/crypt*"
PKG_CUSTOM_INSTALL="make -R GIT=false prefix=/usr install"
