PKG_NAME="markupsafe"
PKG_VER="3.0.3"
PKG_URL1="https://pypi.org/packages/source/M/MarkupSafe/markupsafe-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_DIR="MarkupSafe-${PKG_VER}"
PKG_CUSTOM_BUILD="pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps \$PWD"
PKG_CUSTOM_INSTALL="pip3 install --no-index --find-links dist --force-reinstall --no-deps Markupsafe"
