PKG_NAME="mbedtls"
PKG_VER="4.2.0"
PKG_URL1="https://github.com/Mbed-TLS/mbedtls/releases/download/mbedtls-${PKG_VER}/mbedtls-${PKG_VER}.tar.bz2"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib64 -DUSE_SHARED_MBEDTLS_LIBRARY=ON -DUSE_STATIC_MBEDTLS_LIBRARY=ON -DENABLE_TESTING=OFF -DENABLE_PROGRAMS=ON"
