PKG_NAME="mesa-demos"
PKG_VER="9.0.0"
PKG_URL1="https://archive.mesa3d.org/demos/mesa-demos-${PKG_VER}.tar.xz"
PKG_TARBALL="mesa-demos-${PKG_VER}.tar.gz"
PKG_DIR="mesa-demos-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="a4076679b6d5391700c795158515ee53d9c3701849c74aadf7cf944dda1faa5d"
