PKG_NAME="mesa"
PKG_VER="26.1.2"
PKG_URL1="https://archive.mesa3d.org/mesa-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/mesa-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dplatforms=x11,wayland \
  -Dgallium-drivers=softpipe \
  -Dvulkan-drivers=[] \
  -Dglx=dri \
  -Dgbm=enabled \
  -Degl=enabled \
  \
  -Dgles1=disabled \
  -Dgles2=enabled \
  -Dllvm=disabled \
 "
PKG_POST_INSTALL="ln -sf /usr/lib64/libgallium-${PKG_VER}.so /usr/lib64/libgallium.so || true"
