PKG_NAME="mpv"
PKG_VER="0.41.0"
PKG_URL1="https://github.com/mpv-player/mpv/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/mpv-player/mpv/releases/download/v${PKG_VER}/mpv-${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="mpv-${PKG_VER}.tar.gz"
PKG_MESON_OPTS="-Dlua=luajit \
  -Ddrm=enabled \
  -Dwayland=enabled \
  -Dx11=enabled \
  -Dvulkan=enabled \
  -Dvaapi=enabled \
  -Dvaapi-drm=enabled \
  -Dvaapi-wayland=enabled \
  -Dvaapi-x11=enabled \
  -Dlcms2=enabled \
  -Dlibarchive=enabled \
  -Dalsa=enabled \
  -Dpulse=enabled \
  -Dpipewire=enabled \
  -Dsdl2-video=enabled \
  -Dlibmpv=true \
  -Dgl=enabled \
  -Degl=enabled \
  -Degl-drm=enabled \
  -Degl-wayland=enabled \
  -Degl-x11=enabled \
  -Dgl-x11=enabled \
  -Dvdpau=disabled \
  -Ddvdnav=disabled \
  -Drubberband=disabled \
  -Duchardet=disabled \
  -Dzimg=disabled \
  -Dvapoursynth=disabled \
  -Djack=disabled \
  -Dcdda=disabled"
PKG_SHA256="ee21092a5ee427353392360929dc64645c54479aefdb5babc5cfbb5fad626209"
