PKG_NAME="ninja"
PKG_VER="1.13.2"
PKG_URL1="https://github.com/ninja-build/ninja/archive/v${PKG_VER}/ninja-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="python3 configure.py --bootstrap --verbose"
PKG_CUSTOM_INSTALL="install -vm755 ninja /usr/bin/ && install -vDm644 misc/bash-completion /usr/share/bash-completion/completions/ninja && install -vDm644 misc/zsh-completion /usr/share/zsh/site-functions/_ninja"
