PKG_NAME="nv-codec-headers"
PKG_VER="13.1.15.0"
PKG_URL1="https://github.com/FFmpeg/nv-codec-headers/releases/download/n${PKG_VER}/nv-codec-headers-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="echo 'headers only'"
PKG_CUSTOM_INSTALL="make PREFIX=/usr install"
