PKG_NAME="nvidia-vaapi-driver"
PKG_VER="0.0.17"
PKG_URL1="https://github.com/elFarto/nvidia-vaapi-driver/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="nvidia-vaapi-driver-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
