PKG_NAME="nvme-cli"
PKG_VER="3.0"
PKG_URL1="https://github.com/linux-nvme/nvme-cli/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Ddocs=false -Dudevrulesdir=/usr/lib/udev/rules.d"
