PKG_NAME="openresolv"
PKG_VER="3.17.4"
PKG_URL1="https://github.com/NetworkConfiguration/openresolv/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS=""
