PKG_NAME="openssl"
PKG_VER="3.6.1"
PKG_URL1="https://github.com/openssl/openssl/releases/download/openssl-${PKG_VER}/openssl-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib shared zlib-dynamic && make"
PKG_CUSTOM_INSTALL="sed -i '/INSTALL_LIBS/s/libcrypto.a libssl.a//' Makefile && make MANSUFFIX=ssl install && mv -v /usr/share/doc/openssl /usr/share/doc/openssl-${PKG_VER}"
