PKG_NAME="packaging"
PKG_VER="26.2"
PKG_URL1="https://files.pythonhosted.org/packages/source/p/packaging/packaging-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="pip3 wheel -w dist --no-cache-dir --no-build-isolation --no-deps \$PWD"
PKG_CUSTOM_INSTALL="pip3 install --no-index --find-links dist --force-reinstall --no-deps packaging"
PKG_SHA256="ff452ff5a3e828ce110190feff1178bb1f2ea2281fa2075aadb987c2fb221661"
