PKG_NAME="pango"
PKG_VER="1.57.1"
PKG_URL1="https://download.gnome.org/sources/pango/${PKG_VER%.*}/pango-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dbuild-testsuite=false -Dbuild-examples=false -Ddocumentation=false -Dintrospection=enabled -Dfreetype=enabled -Dcairo=enabled"
