PKG_NAME="pipewire"
PKG_VER="1.6.7"
PKG_URL1="https://gitlab.freedesktop.org/pipewire/pipewire/-/archive/${PKG_VER}/pipewire-${PKG_VER}.tar.gz"
PKG_URL2="https://github.com/PipeWire/pipewire/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_URL3=""
PKG_TARBALL="pipewire-${PKG_VER}.tar.gz"
PKG_MESON_OPTS="-Dalsa=enabled \
  -Dlibpulse=enabled \
  -Dbluez5=disabled \
  -Dgstreamer=enabled \
  -Dx11=enabled \
   \
  -Draop=enabled \
  -Djack=disabled \
  -Dffmpeg=disabled \
  -Davahi=disabled \
  -Dlibcanberra=disabled \
  -Ddocs=disabled \
  -Dtests=disabled \
  -Dexamples=disabled"
PKG_POST_INSTALL="
    sudo -u tertol XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemctl --user daemon-reload
    sudo -u tertol XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus systemctl --user restart pipewire pipewire-pulse wireplumber
"
