PKG_NAME="pkgconf"
PKG_VER="2.5.1"
PKG_URL1="https://distfiles.ariadne.space/pkgconf/pkgconf-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS="--disable-static --docdir=/usr/share/doc/pkgconf-${PKG_VER}"
PKG_POST_INSTALL="ln -sfv pkgconf /usr/bin/pkg-config && ln -sfv pkgconf.1 /usr/share/man/man1/pkg-config.1"
PKG_SHA256="cd05c9589b9f86ecf044c10a2269822bc9eb001eced2582cfffd658b0a50c243"
