PKG_NAME="playerctl"
PKG_VER="2.4.1"
PKG_URL1="https://github.com/altdesktop/playerctl/archive/refs/tags/v${PKG_VER}/playerctl-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dintrospection=false -Dgtk-doc=false"
