PKG_NAME="polkit"
PKG_VER="127"
PKG_URL1="https://github.com/polkit-org/polkit/archive/refs/tags/${PKG_VER}/polkit-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false -Dgtk_doc=false -Dintrospection=true -Dman=false -Dos_type=lfs"
