# /etc/bogartpkg/packages.d/poppler.conf
PKG_NAME="poppler"
PKG_VER="26.06.0"
PKG_URL1="https://poppler.freedesktop.org/poppler-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/poppler-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_CMAKE_OPTS="-DENABLE_NSS3=OFF -DENABLE_GPGME=OFF"
PKG_SHA256="6fef27ff04f37db43054c86bcdff6128c9fb1f6af4ef3c8b369a7e9abd68d0bb"
