PKG_NAME="porg"
PKG_VER="0.10"
PKG_URL1="https://github.com/drfiemost/porg/archive/refs/tags/${PKG_VER}/porg-${PKG_VER}.tar.gz"
PKG_TARBALL="porg-${PKG_VER}.tar.gz"
PKG_DIR="porg-${PKG_VER}"
PKG_PRE_BUILD="autoreconf -fi"
PKG_OPTS="--sysconfdir=/etc --disable-grop"
