PKG_NAME="procps-ng"
PKG_VER="4.0.6"
PKG_URL1="https://sourceforge.net/projects/procps-ng/files/Production/procps-ng-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_OPTS="--docdir=/usr/share/doc/procps-ng-${PKG_VER} --disable-static --disable-kill --with-systemd"
