PKG_NAME="protobuf"
PKG_VER="35.0"
PKG_URL1="https://github.com/protocolbuffers/protobuf/releases/download/v${PKG_VER}/protobuf-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="mkdir -p build && cd build && cmake -D CMAKE_INSTALL_PREFIX=/usr -D CMAKE_BUILD_TYPE=Release -D CMAKE_SKIP_INSTALL_RPATH=ON -D protobuf_BUILD_TESTS=OFF -D protobuf_BUILD_SHARED_LIBS=ON -D protobuf_FORCE_FETCH_DEPENDENCIES=ON -G Ninja .. && ninja"
PKG_CUSTOM_INSTALL="cd build && ninja install"
