PKG_NAME="protobuf"
PKG_VER="35.0"
PKG_URL1="https://github.com/protocolbuffers/protobuf/releases/download/v${PKG_VER}/protobuf-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-Dprotobuf_BUILD_SHARED_LIBS=ON -Dprotobuf_BUILD_TESTS=OFF -DCMAKE_CXX_STANDARD=23 -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
PKG_JOBS=1
