PKG_NAME="psmisc"
PKG_VER="23.7"
PKG_URL1="https://sourceforge.net/projects/psmisc/files/psmisc/psmisc-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_SHA256="58c55d9c1402474065adae669511c191de374b0871eec781239ab400b907c327"
