PKG_NAME="pugixml"
PKG_VER="1.16"
PKG_URL1="https://github.com/zeux/pugixml/releases/download/v${PKG_VER}/pugixml-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_SHARED_LIBS=ON -DPUGIXML_BUILD_TESTS=OFF"
