PKG_NAME="pulseaudio"
PKG_VER="17.0"
PKG_URL1="https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/archive/v${PKG_VER}/pulseaudio-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Ddaemon=false -Ddoxygen=false -Dman=false -Dtests=false"
PKG_PRE_BUILD="echo ${PKG_VER} > .tarball-version"
PKG_SRC_DIR="pulseaudio-v${PKG_VER}"
PKG_SHA256="5baa9c2cb382f052c113dec7ec9cccdd7aa82829f49b8879f32b98d5ca7804fc"
