PKG_NAME="pygobject"
PKG_VER="3.56.3"
PKG_URL1="https://gitlab.gnome.org/GNOME/pygobject/-/archive/${PKG_VER}/pygobject-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false"
PKG_SHA256="ad8b72852db4147cafed8bb4576a0ee6e5903a93b74745408f98148ac1efc344"
