PKG_NAME="pygobject"
PKG_VER="3.56.3"
PKG_URL1="https://gitlab.gnome.org/GNOME/pygobject/-/archive/${PKG_VER}/pygobject-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false"
