PKG_NAME="python-cryptography"
PKG_VER="50.0.0"
PKG_URL1="https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="/usr/bin/pip3 install --no-cache-dir --break-system-packages cryptography==${PKG_VER}"
