PKG_NAME="python-ollama"
PKG_VER="0.6.2"
PKG_URL1="https://pypi.org/pypi/ollama/${PKG_VER}/json"
PKG_TARBALL="python-ollama-${PKG_VER}.json"
PKG_SKIP_EXTRACT="1"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="echo 'pip managed'"
PKG_CUSTOM_INSTALL="pip3 install --break-system-packages ollama==${PKG_VER}"
