PKG_NAME="python"
PKG_VER="3.14.6"
PKG_URL1="https://www.python.org/ftp/python/${PKG_VER}/Python-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_DIR="Python-${PKG_VER}"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --enable-shared --with-system-expat --enable-optimizations --without-static-libpython && make"
PKG_CUSTOM_INSTALL="make install && cat > /etc/pip.conf << 'PIPEOF'
[global]
root-user-action = ignore
disable-pip-version-check = true
PIPEOF"
