PKG_NAME="qemu"
PKG_VER="11.0.1"
PKG_URL1="https://download.qemu.org/qemu-${PKG_VER}.tar.xz"
PKG_TARBALL="qemu-${PKG_VER}.tar.xz"
PKG_DIR="qemu-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_PRE_BUILD="./configure --prefix=/usr --enable-kvm --enable-virtfs \
    --enable-virglrenderer --enable-opengl --enable-slirp \
    --audio-drv-list=pipewire,alsa --disable-spice --disable-docs \
    --enable-plugins --python=/usr/bin/python3"
PKG_MESON_OPTS="-Dkvm=enabled \
    -Dvirtfs=enabled \
    -Dvirglrenderer=enabled \
    -Dopengl=enabled \
    -Dslirp=enabled \
    -Daudio_drv_list=pipewire,alsa \
    -Dspice=disabled \
    -Ddocs=disabled \
    -Dplugins=true \
    -Dgdb=/usr/bin/gdb"
PKG_POST_INSTALL="chmod u+s /usr/libexec/qemu-bridge-helper"
