PKG_NAME="qt5"
PKG_VER="5.15.16"
PKG_URL1="https://download.qt.io/official_releases/qt/${PKG_VER%*.*}/${PKG_VER}/single/qt-everywhere-opensource-src-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_TARBALL="qt-everywhere-opensource-src-${PKG_VER}.tar.xz"
PKG_DIR="qt-everywhere-opensource-src-${PKG_VER}"
PKG_PREFIX="/opt/qt5"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="./configure --prefix=/opt/qt5 -opensource -confirm-license -nomake examples -nomake tests -skip qtwebengine -skip qtlocation -no-pch &&  make -j$(nproc)"
PKG_CUSTOM_INSTALL="make install"
