PKG_NAME="qt6"
PKG_VER="6.11.1"
PKG_URL1="https://download.qt.io/official_releases/qt/${PKG_VER%.*}/${PKG_VER}/single/qt-everywhere-src-${PKG_VER}.tar.xz"
PKG_URL2="https://mirrors.kernel.org/gentoo/distfiles/qt-everywhere-src-${PKG_VER}.tar.xz"
PKG_URL3=""
PKG_PREFIX="/opt/qt6"
PKG_CMAKE_OPTS="-DBUILD_qtwebengine=OFF -DBUILD_qtlocation=OFF -DBUILD_TESTING=OFF"
PKG_SHA256="252acef8c5ae68074d91cadba2ee4a83465051bbb970dd26e8f0daa0f3904e03"
