PKG_NAME="re2"
PKG_VER="2025.11.05"
PKG_URL1="https://github.com/google/re2/archive/refs/tags/2025-11-05/re2-2025.11.05.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_TARBALL="re2-2025.11.05.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/re2 /usr/lib64/libre2* /usr/lib64/cmake/re2 /usr/lib64/pkgconfig/re2.pc"
PKG_CMAKE_OPTS="-DBUILD_SHARED_LIBS=ON \
  -DRE2_BUILD_TESTING=OFF"
