PKG_NAME="readline"
PKG_VER="8.3"
PKG_URL1="https://ftpmirror.gnu.org/readline/readline-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="sed -i '/MV.*old/d' Makefile.in && sed -i '/{OLDSUFF}/c:' support/shlib-install && sed -i 's/-Wl,-rpath,[^ ]*//' support/shobj-conf"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --disable-static --with-curses --docdir=/usr/share/doc/readline-${PKG_VER} && make SHLIB_LIBS='-lncursesw'"
PKG_CUSTOM_INSTALL="make install"
PKG_SHA256="fe5383204467828cd495ee8d1d3c037a7eba1389c22bc6a041f627976f9061cc"
