PKG_NAME="rofi-wayland"
PKG_VER="1.7.9"
PKG_URL1="https://github.com/lbonn/rofi/releases/download/${PKG_VER}%2Bwayland1/rofi-${PKG_VER}%2Bwayland1.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dcheck=disabled"
PKG_SRC_DIR="rofi-${PKG_VER}+wayland1"
PKG_SHA256="edeb12479e759de6a1734f62237605d79baef43d610d5af687b337e98756b74e"
