PKG_NAME="rsync"
PKG_VER="3.4.4"
PKG_URL1="https://download.samba.org/pub/rsync/src/rsync-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-lz4 --disable-xxhash --without-included-zlib"
