PKG_NAME="rusty-psn"
PKG_VER="0.5.10"
PKG_URL1="https://github.com/RainbowCookie32/rusty-psn/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="rusty-psn-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -m755 target/release/rusty-psn /usr/bin/rusty-psn"
