PKG_NAME="scdoc"
PKG_VER="1.11.5"
PKG_URL1="https://git.sr.ht/~sircmpwn/scdoc/archive/${PKG_VER}.tar.gz"
PKG_TARBALL="scdoc-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make PREFIX=/usr"
PKG_CUSTOM_INSTALL="make PREFIX=/usr install"
