PKG_NAME="sdbus-cpp"
PKG_VER="2.3.1"
PKG_URL1="https://github.com/Kistler-Group/sdbus-cpp/archive/refs/tags/v${PKG_VER}/sdbus-cpp-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTS=OFF -DBUILD_CODE_GEN=OFF"
