PKG_NAME="sdl2-compat"
PKG_VER="2.32.70"
PKG_URL1="https://github.com/libsdl-org/sdl2-compat/releases/download/release-${PKG_VER}/sdl2-compat-${PKG_VER}.tar.gz"
PKG_URL2="https://codeload.github.com/libsdl-org/sdl2-compat/tar.gz/refs/tags/release-${PKG_VER}"
PKG_URL3=""
PKG_TARBALL="sdl2-compat-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/lib64/cmake/SDL2 /usr/lib64/libSDL2* /usr/lib64/pkgconfig/sdl2-compat.pc /usr/include/SDL2 /usr/bin/sdl2-config /usr/share/aclocal/sdl2.m4"
PKG_CMAKE_OPTS="-DSDL2COMPAT_TESTS=OFF"
