PKG_NAME="sdl3"
PKG_VER="3.4.12"
PKG_URL1="https://github.com/libsdl-org/SDL/releases/download/release-${PKG_VER}/SDL3-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DCMAKE_INSTALL_LIBDIR=lib"
PKG_PRE_BUILD="rm -rf /usr/lib64/libSDL3* /usr/lib64/pkgconfig/sdl3.pc /usr/lib64/cmake/SDL3 /usr/include/SDL3"
