PKG_NAME="seatd"
PKG_VER="0.9.3"
PKG_URL1="https://git.sr.ht/~kennylevinsen/seatd/archive/${PKG_VER}.tar.gz"
PKG_TARBALL="seatd-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dserver=enabled -Dlibseat-builtin=enabled -Dlibseat-logind=systemd"
