PKG_NAME="sed"
PKG_VER="4.10"
PKG_URL1="https://ftp.gnu.org/gnu/sed/sed-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS=""
PKG_POST_INSTALL=""
PKG_SHA256="b8e72182b2ec96a3574e2998c47b7aaa64cc20ce000d8e9ac313cc07cecf28c7"
