PKG_NAME="shadow"
PKG_VER="4.19.3"
PKG_URL1="https://github.com/shadow-maint/shadow/releases/download/${PKG_VER}/shadow-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="sed -i 's/groups\$(EXEEXT) //' src/Makefile.in && find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \; && find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \; && find man -name Makefile.in -exec sed -i 's/passwd\.5 / /' {} \; && sed -e 's@#ENCRYPT_METHOD DES@ENCRYPT_METHOD YESCRYPT@' -e 's@/var/spool/mail@/var/mail@' -e '/PATH=/{s@/sbin:@@;s@/bin:@@}' -i etc/login.defs && ./configure --sysconfdir=/etc --disable-static --without-libbsd --with-{b,yes}crypt"
PKG_CUSTOM_BUILD="make"
PKG_CUSTOM_INSTALL="make exec_prefix=/usr pamddir= install && make -C man install-man"
PKG_SHA256="11a8f358910712cf957dd4fd205063fce7e386b68fc7dfe3a0e1e53155ec53c5"
