PKG_NAME="shaderc"
PKG_VER="2026.3"
PKG_URL1="https://codeload.github.com/google/shaderc/tar.gz/refs/tags/v${PKG_VER}"
PKG_TARBALL="shaderc-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/shaderc /usr/lib64/libshaderc* /usr/lib64/pkgconfig/shaderc* /usr/bin/glslc && git clone https://github.com/KhronosGroup/glslang.git third_party/glslang && git -C third_party/glslang checkout 168d452a4f460d24b588fed08477a81c44ee27a1 && git clone https://github.com/KhronosGroup/SPIRV-Tools.git third_party/spirv-tools && git -C third_party/spirv-tools checkout b707790a898e44038547df54580022fc1cf89c3d && git clone https://github.com/KhronosGroup/SPIRV-Headers.git third_party/spirv-headers && git -C third_party/spirv-headers checkout 29981f65241605e08b0ede4cfeb999fe3b723c6a"
PKG_CMAKE_OPTS="-DSHADERC_SKIP_TESTS=ON -DSHADERC_SKIP_EXAMPLES=ON -DSHADERC_ENABLE_SHARED_CRT=ON -DCMAKE_INSTALL_LIBDIR=lib64"
