PKG_NAME="shared-mime-info"
PKG_VER="2.4"
PKG_URL1="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${PKG_VER}/shared-mime-info-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dupdate-mimedb=true -Dbuild-tests=false"
PKG_SHA256="531291d0387eb94e16e775d7e73788d06d2b2fdd8cd2ac6b6b15287593b6a2de"
