PKG_NAME="shared-mime-info"
PKG_VER="2.5.1"
PKG_URL1="https://gitlab.freedesktop.org/xdg/shared-mime-info/-/archive/${PKG_VER}/shared-mime-info-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dupdate-mimedb=true -Dbuild-tests=false"
