PKG_NAME="snapper"
PKG_VER="0.13.1"
PKG_URL1="https://github.com/openSUSE/snapper/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="snapper-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_PRE_BUILD="libtoolize --force && aclocal && autoheader && autoconf && automake --add-missing"
PKG_OPTS="--disable-static --disable-zypp --disable-pam --disable-doc"
