PKG_NAME="spice"
PKG_VER="0.16.0"
PKG_URL1="https://www.spice-space.org/download/releases/spice-${PKG_VER}.tar.bz2"
PKG_TARBALL="spice-${PKG_VER}.tar.bz2"
PKG_DIR="spice-${PKG_VER}"
PKG_OPTS="--disable-static"
