PKG_NAME="spice"
PKG_VER="0.16.0"
PKG_URL1="https://www.spice-space.org/download/releases/spice-${PKG_VER}.tar.bz2"
PKG_TARBALL="spice-${PKG_VER}.tar.bz2"
PKG_DIR="spice-${PKG_VER}"
PKG_OPTS="--disable-static"
PKG_SHA256="0a6ec9528f05371261bbb2d46ff35e7b5c45ff89bb975a99af95a5f20ff4717d"
