PKG_NAME="spirv-tools"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="spirv-tools-${PKG_VER}.tar.gz"
PKG_DIR="SPIRV-Tools-vulkan-sdk-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/spirv-tools /usr/lib64/cmake/SPIRV-Tools* /usr/lib64/libSPIRV-Tools*.so* /usr/lib64/pkgconfig/SPIRV-Tools*.pc /usr/bin/spirv-as /usr/bin/spirv-cfg /usr/bin/spirv-diff /usr/bin/spirv-dis /usr/bin/spirv-lesspipe.sh /usr/bin/spirv-link /usr/bin/spirv-lint /usr/bin/spirv-objdump /usr/bin/spirv-opt /usr/bin/spirv-reduce /usr/bin/spirv-val"
PKG_CMAKE_OPTS="-DSPIRV_SKIP_TESTS=ON -DSPIRV-Headers_SOURCE_DIR=/usr -DBUILD_SHARED_LIBS=ON -DSPIRV_TOOLS_BUILD_STATIC=OFF"
