PKG_NAME="spirv-headers"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="spirv-headers-${PKG_VER}.tar.gz"
PKG_DIR="SPIRV-Headers-vulkan-sdk-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/spirv /usr/share/cmake/SPIRV-Headers /usr/share/pkgconfig/SPIRV-Headers.pc"
PKG_CMAKE_OPTS="-DSPIRV_HEADERS_SKIP_EXAMPLES=ON"
