PKG_NAME="sqlite"
PKG_VER="3510200"
PKG_URL1="https://sqlite.org/2026/sqlite-autoconf-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_DIR="sqlite-autoconf-${PKG_VER}"
PKG_CUSTOM_BUILD="./configure --prefix=/usr --disable-static --enable-fts4 --enable-fts5 CPPFLAGS='-DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1 -DSQLITE_SECURE_DELETE=1' && make LDFLAGS.rpath=''"
PKG_CUSTOM_INSTALL="make install"
PKG_SHA256="fbd89f866b1403bb66a143065440089dd76100f2238314d92274a082d4f2b7bb"
