PKG_NAME="squashfs-tools"
PKG_VER="4.7.5"
PKG_URL1="https://github.com/plougher/squashfs-tools/releases/download/${PKG_VER}/squashfs-tools-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make -C squashfs-tools -j$(nproc)"
PKG_CUSTOM_INSTALL="make -C squashfs-tools install INSTALL_DIR=/usr/bin"
