PKG_NAME="sudo"
PKG_VER="1.9.17p2"
PKG_URL1="https://www.sudo.ws/dist/sudo-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--libexecdir=/usr/lib --with-secure-path --with-all-insults --with-env-editor --with-passprompt='[sudo] password for %p: '"
PKG_POST_INSTALL="printf '#%%PAM-1.0\nauth      include    system-auth\naccount   include    system-account\nsession   include    system-session\n' > /etc/pam.d/sudo"
