PKG_NAME="suricata"
PKG_VER="8.0.6"
PKG_URL1="https://www.openinfosecfoundation.org/download/suricata-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-nfqueue --disable-doc --enable-modbus --enable-dnp3"
PKG_POST_INSTALL="mkdir -p /usr/etc/suricata && suricata --dump-config > /usr/etc/suricata/suricata.yaml; mkdir -p /usr/var/log/suricata && mkdir -p /usr/var/lib/suricata/rules"
