PKG_NAME="svt-av1"
PKG_VER="4.2.0"
PKG_URL1="https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v${PKG_VER}/SVT-AV1-v${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LIBDIR=lib64"
PKG_PRE_BUILD="rm -rf /usr/lib64/cmake/SVT-AV1 /usr/lib64/libSvtAv1Enc.so* /usr/lib64/pkgconfig/SvtAv1Enc.pc /usr/include/svt-av1"
