PKG_NAME="swayimg"
PKG_VER="5.3"
PKG_URL1="https://github.com/artemsen/swayimg/archive/refs/tags/v${PKG_VER}/swayimg-${PKG_VER}.tar.gz"
PKG_TARBALL="swayimg-${PKG_VER}.tar.gz"
PKG_DIR="swayimg-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
