PKG_NAME="swig"
PKG_VER="4.5.0"
PKG_URL1="https://sourceforge.net/projects/swig/files/swig/swig-${PKG_VER}/swig-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--without-alllang --with-python3"
