PKG_NAME="swww"
PKG_VER="0.11.2"
PKG_URL1="https://github.com/LGFae/swww/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="swww-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="python3 -c \"
import re
f='/root/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/waybackend-scanner-0.6.2/src/lib.rs'
try:
    c=open(f).read()
    c=c.replace('e => panic!(\\n                        \\\"unrecognized attribute in interface: {}\\\",\\n                        String::from_utf8_lossy(e)\\n                    ),','e => {}  // ignore unknown attributes')
    open(f,'w').write(c)
except: pass
\""
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -m755 target/release/swww target/release/swww-daemon /usr/bin/"
