PKG_NAME="sysstat"
PKG_VER="12.8.0"
PKG_URL1="https://github.com/sysstat/sysstat/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-nls --enable-install-cron --enable-compress-manpg=no"
