PKG_NAME="systemd"
PKG_VER="260.1"
PKG_URL1="https://github.com/systemd/systemd/archive/v${PKG_VER}/systemd-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_PRE_BUILD="sed -e 's/GROUP=\"render\"/GROUP=\"video\"/' -e 's/GROUP=\"sgx\", //' -i rules.d/50-udev-default.rules.in"
PKG_CUSTOM_BUILD="mkdir -p build && cd build && meson setup .. --prefix=/usr --buildtype=release -D default-dnssec=no -D firstboot=false -D install-tests=false -D ldconfig=false -D sysusers=true -D rpmmacrosdir=no -D homed=disabled -D man=disabled -D mode=release -D pamconfdir=no -D dev-kvm-mode=0660 -D nobody-group=nogroup -D sysupdate=disabled -D ukify=disabled -D docdir=/usr/share/doc/systemd-${PKG_VER} -D standalone-binaries=true && ninja"
PKG_CUSTOM_INSTALL="cd build && ninja install && systemd-machine-id-setup && systemctl preset-all"
