PKG_NAME="tailscale"
PKG_VER="1.98.4"
PKG_URL1="https://pkgs.tailscale.com/stable/tailscale_${PKG_VER}_amd64.tgz"
PKG_TARBALL="tailscale-${PKG_VER}.tar.gz"
PKG_DIR="tailscale_${PKG_VER}_amd64"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="install -m755 tailscale tailscaled /usr/bin/"
