PKG_NAME="tar"
PKG_VER="1.35"
PKG_URL1="https://ftpmirror.gnu.org/tar/tar-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr && make"
PKG_CUSTOM_INSTALL="make install && make -C doc install-html docdir=/usr/share/doc/tar-${PKG_VER}"
