PKG_NAME="tcl"
PKG_VER="8.6.17"
PKG_URL1="https://downloads.sourceforge.net/tcl/tcl${PKG_VER}-src.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_DIR="tcl${PKG_VER}"
PKG_CUSTOM_BUILD="SRCDIR=\$(pwd) && cd unix && ./configure --prefix=/usr --mandir=/usr/share/man --disable-rpath && make && sed -e \"s|\$SRCDIR/unix|/usr/lib|\" -e \"s|\$SRCDIR|/usr/include|\" -i tclConfig.sh && sed -e \"s|\$SRCDIR/unix/pkgs/tdbc1.1.12|/usr/lib/tdbc1.1.12|\" -e \"s|\$SRCDIR/pkgs/tdbc1.1.12/generic|/usr/include|\" -e \"s|\$SRCDIR/pkgs/tdbc1.1.12/library|/usr/lib/tcl8.6|\" -e \"s|\$SRCDIR/pkgs/tdbc1.1.12|/usr/include|\" -i pkgs/tdbc1.1.12/tdbcConfig.sh && sed -e \"s|\$SRCDIR/unix/pkgs/itcl4.3.4|/usr/lib/itcl4.3.4|\" -e \"s|\$SRCDIR/pkgs/itcl4.3.4/generic|/usr/include|\" -e \"s|\$SRCDIR/pkgs/itcl4.3.4|/usr/include|\" -i pkgs/itcl4.3.4/itclConfig.sh"
PKG_CUSTOM_INSTALL="cd unix && make install && chmod 644 /usr/lib/libtclstub8.6.a && chmod -v u+w /usr/lib/libtcl8.6.so && make install-private-headers && ln -sfv tclsh8.6 /usr/bin/tclsh && mv -v /usr/share/man/man3/{Thread,Tcl_Thread}.3"
PKG_SHA256="a3903371efcce8a405c5c245d029e9f6850258a60fa3761c4d58995610949b31"
