PKG_NAME="terraform"
PKG_VER="1.15.8"
PKG_URL1="https://releases.hashicorp.com/terraform/${PKG_VER}/terraform_${PKG_VER}_linux_amd64.zip"
PKG_TARBALL="terraform_${PKG_VER}_linux_amd64.zip"
PKG_STRIP_COMPONENTS="0"
PKG_SKIP_EXTRACT="1"
PKG_CASCADE_SKIP="binary-only"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="unzip -o terraform_${PKG_VER}_linux_amd64.zip"
PKG_CUSTOM_INSTALL="install -m755 terraform /usr/local/bin/terraform"
