PKG_NAME="upower"
PKG_VER="1.91.2"
PKG_URL1="https://gitlab.freedesktop.org/upower/upower/-/archive/v${PKG_VER}/upower-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dman=false -Dgtk-doc=false"
PKG_SRC_DIR="upower-v${PKG_VER}"
