PKG_NAME="upower"
PKG_VER="1.91.2"
PKG_URL1="https://gitlab.freedesktop.org/upower/upower/-/archive/v${PKG_VER}/upower-${PKG_VER}.tar.bz2"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dman=false -Dgtk-doc=false"
PKG_SRC_DIR="upower-v${PKG_VER}"
PKG_SHA256="f2e62a4f0b74115dbc00fc16362f9b50c8f85d4c48ec24ac16f8d2f3f2ca68b8"
