PKG_NAME="usb-modeswitch"
PKG_VER="2.6.2"
PKG_URL1="https://www.draisberghof.de/usb_modeswitch/usb-modeswitch-${PKG_VER}.tar.bz2"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make"
PKG_CUSTOM_INSTALL="make install"
