PKG_NAME="usbguard"
PKG_VER="1.1.4"
PKG_URL1="https://github.com/USBGuard/usbguard/releases/download/usbguard-${PKG_VER}/usbguard-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="PKG_CONFIG_PATH=/usr/lib64/pkgconfig:/usr/lib/pkgconfig:/usr/local/lib/pkgconfig:/usr/share/pkgconfig ./configure --prefix=/usr --sysconfdir=/etc --with-crypto-library=openssl --enable-systemd --without-dbus --disable-silent-rules --with-bundled-catch --with-bundled-pegtl && make -j\$(nproc) -k || true"
PKG_CUSTOM_INSTALL="make install-binPROGRAMS install-sbinPROGRAMS install-libLTLIBRARIES install-pkgincludeHEADERS install-pkgconfigDATA install-dist_bashcompletionDATA"
