PKG_NAME="usbguard"
PKG_VER="1.1.4"
PKG_URL1="https://github.com/USBGuard/usbguard/releases/download/usbguard-${PKG_VER}/usbguard-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--sysconfdir=/etc --with-crypto-library=openssl --enable-systemd --without-dbus --disable-silent-rules --with-bundled-catch --with-bundled-pegtl"
