PKG_NAME="usbutils"
PKG_VER="019"
PKG_URL1="https://github.com/gregkh/usbutils/archive/refs/tags/v${PKG_VER}/usbutils-${PKG_VER}.tar.gz"
PKG_TARBALL="usbutils-${PKG_VER}.tar.gz"
PKG_DIR="usbutils-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
