PKG_NAME="usbutils"
PKG_VER="019"
PKG_URL1="https://github.com/gregkh/usbutils/archive/refs/tags/v${PKG_VER}/usbutils-${PKG_VER}.tar.gz"
PKG_TARBALL="usbutils-${PKG_VER}.tar.gz"
PKG_DIR="usbutils-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="f0df341a2125a4bdf2f88c77c3828af9f24c2d58e30928c45b23f41e1315df7a"
