PKG_NAME="vulkan-tools"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/Vulkan-Tools/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="vulkan-tools-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="cmake"
