PKG_NAME="vulkan-loader"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/Vulkan-Loader/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="vulkan-loader-${PKG_VER}.tar.gz"
PKG_DIR="Vulkan-Loader-vulkan-sdk-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/lib64/cmake/VulkanLoader /usr/lib64/libvulkan.so* /usr/lib64/pkgconfig/vulkan.pc"
PKG_CMAKE_OPTS="-DUPDATE_DEPS=OFF"
