PKG_NAME="vulkan-headers"
PKG_VER="1.4.350.1"
PKG_URL1="https://github.com/KhronosGroup/Vulkan-Headers/archive/refs/tags/vulkan-sdk-${PKG_VER}.tar.gz"
PKG_TARBALL="vulkan-headers-${PKG_VER}.tar.gz"
PKG_DIR="Vulkan-Headers-vulkan-sdk-${PKG_VER}"
PKG_BUILD_TYPE="cmake"
PKG_PRE_BUILD="rm -rf /usr/include/vulkan /usr/include/vk_video /usr/share/cmake/VulkanHeaders /usr/share/pkgconfig/vulkan.pc /usr/lib*/pkgconfig/vulkan.pc /usr/share/vulkan"
