PKG_NAME="waypipe"
PKG_VER="0.11.0"
PKG_URL1="https://gitlab.freedesktop.org/mstoeckl/waypipe/-/archive/v${PKG_VER}/waypipe-v${PKG_VER}.tar.gz"
PKG_TARBALL="waypipe-v${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dman-pages=disabled -Drust_executable=disabled"
PKG_PRE_BUILD="cargo fetch"
