PKG_NAME="wazuh-agent"
PKG_VER="4.14.7"
PKG_URL1="https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_${PKG_VER}-1_amd64.deb"
PKG_TARBALL="wazuh-agent_${PKG_VER}-1_amd64.deb"
PKG_STRIP_COMPONENTS="0"
PKG_SKIP_EXTRACT="1"
PKG_CASCADE_SKIP="binary-only"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="ar x wazuh-agent_${PKG_VER}-1_amd64.deb"
PKG_CUSTOM_INSTALL="tar -xzf data.tar.gz -C / && groupadd -r wazuh 2>/dev/null; useradd -r -g wazuh -d /var/ossec -s /sbin/nologin wazuh 2>/dev/null; chown -R wazuh:wazuh /var/ossec/queue/ /var/ossec/var/ && systemctl daemon-reload && systemctl enable wazuh-agent"
