PKG_NAME="wget"
PKG_VER="1.25.0"
PKG_URL1="https://ftp.gnu.org/gnu/wget/wget-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--sysconfdir=/etc --with-ssl=openssl"
PKG_SHA256="766e48423e79359ea31e41db9e5c289675947a7fcf2efdcedb726ac9d0da3784"
