PKG_NAME="wireplumber"
PKG_VER="0.5.15"
PKG_URL1="https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/${PKG_VER}/wireplumber-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false"
