PKG_NAME="wireplumber"
PKG_VER="0.5.14"
PKG_URL1="https://gitlab.freedesktop.org/pipewire/wireplumber/-/archive/${PKG_VER}/wireplumber-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dtests=false"
PKG_SHA256="e91f04cd8cec75d72b8a2aaa7e90b1ba0a5e2094b7a882fc3a29a484a48a87e9"
