PKG_NAME="wireless-regdb"
PKG_VER="2026.05.30"
PKG_URL1="https://www.kernel.org/pub/software/network/wireless-regdb/wireless-regdb-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="install -m755 -d /usr/lib/crda/pubkeys && \
    install -m644 regulatory.db regulatory.db.p7s /usr/lib/firmware/ && \
    install -m644 regulatory.bin /usr/lib/crda/ && \
    install -m644 wens.key.pub.pem /usr/lib/crda/pubkeys/"
