PKG_NAME="wireguard-tools"
PKG_VER="1.0.20260223"
PKG_URL1="https://git.zx2c4.com/wireguard-tools/snapshot/wireguard-tools-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make -C src -j$(nproc)"
PKG_CUSTOM_INSTALL="make -C src install"
