PKG_NAME="xdg-desktop-portal-wlr"
PKG_VER="0.8.2"
PKG_URL1="https://github.com/emersion/xdg-desktop-portal-wlr/releases/download/v${PKG_VER}/xdg-desktop-portal-wlr-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dsd-bus-provider=libsystemd"
