PKG_NAME="xdg-desktop-portal"
PKG_VER="1.22.0"
PKG_URL1="https://github.com/flatpak/xdg-desktop-portal/releases/download/${PKG_VER}/xdg-desktop-portal-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dflatpak-interfaces=enabled -Ddbus-service-dir=/usr/share/dbus-1/services -Dsystemd-user-unit-dir=/usr/lib/systemd/user -Dtests=disabled"
PKG_SHA256="a610393a123f9dbd0aed662e716f6f98362850283d2cc750399f12c8313e6564"
