PKG_NAME="xdg-dbus-proxy"
PKG_VER="0.1.7"
PKG_URL1="https://github.com/flatpak/xdg-dbus-proxy/releases/download/${PKG_VER}/xdg-dbus-proxy-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dman=disabled"
PKG_SHA256="3ad3d27ba574e178acb5e4d438ba36ace25e3564f899c36f31c56f82c7adbbe7"
