PKG_NAME="xdg-desktop-portal-hyprland"
PKG_VER="1.4.1"
PKG_URL1="https://github.com/hyprwm/xdg-desktop-portal-hyprland/archive/refs/tags/v${PKG_VER}/xdg-desktop-portal-hyprland-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTING=OFF"
PKG_POST_INSTALL='
mkdir -p /home/tertol/.config/systemd/user
cp /usr/lib/systemd/user/xdg-desktop-portal-hyprland.service /home/tertol/.config/systemd/user/
sed -i "/graphical-session/d" /home/tertol/.config/systemd/user/xdg-desktop-portal-hyprland.service
sed -i "/^ExecStart/i ExecStartPre=/bin/sh -c '\''until [ -S /run/user/1000/wayland-1 ]; do sleep 0.5; done'\''" /home/tertol/.config/systemd/user/xdg-desktop-portal-hyprland.service
printf "\n[Install]\nWantedBy=xdg-desktop-portal.service\n" >> /home/tertol/.config/systemd/user/xdg-desktop-portal-hyprland.service
systemctl --user daemon-reload
systemctl --user enable xdg-desktop-portal-hyprland.service
'
