PKG_NAME="xdg-desktop-portal-hyprland"
PKG_VER="1.3.12"
PKG_URL1="https://github.com/hyprwm/xdg-desktop-portal-hyprland/archive/refs/tags/v${PKG_VER}/xdg-desktop-portal-hyprland-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="cmake"
PKG_CMAKE_OPTS="-DBUILD_TESTING=OFF"
PKG_SHA256="c30ffe6ce9569a222438cb403d426a58c84e3653f19c8de641673097a9acc3b0"
