PKG_NAME="xkeyboard-config"
PKG_VER="2.48"
PKG_URL1="https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/archive/xkeyboard-config-${PKG_VER}/xkeyboard-config-xkeyboard-config-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_TARBALL="xkeyboard-config-xkeyboard-config-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
