PKG_NAME="xml-parser"
PKG_VER="2.59"
PKG_URL1="https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="perl Makefile.PL && make"
PKG_CUSTOM_INSTALL="make install"
