PKG_NAME="xorriso"
PKG_VER="1.5.8"
PKG_URL1="https://ftp.gnu.org/gnu/xorriso/xorriso-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--disable-static"
PKG_SHA256="319e3675cd7d986bf71d36596ca7b03dac172a758462bedcbbd298a7f86f36cc"
