PKG_NAME="xwayland"
PKG_VER="24.1.12"
PKG_URL1="https://xorg.freedesktop.org/archive/individual/xserver/xwayland-${PKG_VER}.tar.xz"
PKG_TARBALL="xwayland-${PKG_VER}.tar.xz"
PKG_DIR="xwayland-${PKG_VER}"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dglamor=true \
    -Dxkb_output_dir=/var/lib/xkb"
PKG_SHA256="6df02c511b92c1b9848734d9d1b03a4c24f8375ba3cada44e9684a21b5f78e21"
