PKG_NAME="xz"
PKG_VER="5.8.2"
PKG_URL1="https://github.com/tukaani-project/xz/releases/download/v${PKG_VER}/xz-${PKG_VER}.tar.xz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_SKIP_AUTOGEN="yes"
PKG_OPTS="--disable-static --docdir=/usr/share/doc/xz-${PKG_VER}"
