PKG_NAME="yazi"
PKG_VER="26.5.6"
PKG_URL1="https://github.com/sxyazi/yazi/archive/refs/tags/v${PKG_VER}.tar.gz"
PKG_TARBALL="yazi-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="cargo build --release"
PKG_CUSTOM_INSTALL="install -m755 target/release/yazi target/release/ya /usr/bin/"
