PKG_NAME="yt-dlp"
PKG_VER="2026.06.09"
PKG_URL1="https://github.com/yt-dlp/yt-dlp/releases/download/${PKG_VER}/yt-dlp"
PKG_TARBALL="yt-dlp"
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="true"
PKG_CUSTOM_INSTALL="install -Dm755 /sources/yt-dlp /usr/local/bin/yt-dlp"
PKG_SKIP_EXTRACT="yes"
