PKG_NAME="zabbix-agent"
PKG_VER="7.4.13"
PKG_URL1="https://cdn.zabbix.com/zabbix/sources/stable/7.0/zabbix-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="autotools"
PKG_OPTS="--enable-agent --with-openssl --sysconfdir=/etc/zabbix --with-libpcre2"
