PKG_NAME="zathura"
PKG_VER="2026.05.20"
PKG_URL1="https://pwmt.org/projects/zathura/download/zathura-${PKG_VER}.tar.xz"
PKG_TARBALL="zathura-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
PKG_SHA256="e2e6dc695ebb0170eaa3d39d295c6997c93f23061e6c2b7d3347e03415a2254b"
