PKG_NAME="zathura-pdf-poppler"
PKG_VER="2026.05.10"
PKG_URL1="https://pwmt.org/projects/zathura-pdf-poppler/download/zathura-pdf-poppler-${PKG_VER}.tar.gz"
PKG_TARBALL="zathura-pdf-poppler-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
