PKG_NAME="zathura"
PKG_VER="2026.05.20"
PKG_URL1="https://pwmt.org/projects/zathura/download/zathura-${PKG_VER}.tar.xz"
PKG_TARBALL="zathura-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS=""
