PKG_NAME="zenity"
PKG_VER="4.2.2"
PKG_URL1="https://github.com/GNOME/zenity/archive/refs/tags/${PKG_VER}.tar.gz"
PKG_TARBALL="zenity-${PKG_VER}.tar.gz"
PKG_BUILD_TYPE="meson"
PKG_MESON_OPTS="-Dmanpage=false"
