PKG_NAME="zig"
PKG_VER="0.16.0"
PKG_URL1="https://ziglang.org/download/${PKG_VER}/zig-x86_64-linux-${PKG_VER}.tar.xz"
PKG_TARBALL="zig-x86_64-linux-${PKG_VER}.tar.xz"
PKG_BUILD_TYPE="custom"
PKG_STRIP_COMPONENTS="1"
PKG_CUSTOM_BUILD="echo 'prebuilt'"
PKG_CUSTOM_INSTALL="rm -rf /usr/local/lib/zig && install -Dm755 zig /usr/local/bin/zig && mkdir -p /usr/local/lib/zig && cp -r lib/. /usr/local/lib/zig/"
