PKG_NAME="zlib"
PKG_VER="1.3.2"
PKG_URL1="https://zlib.net/fossils/zlib-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="autotools"
PKG_CONFIGURE_OPTS=""
PKG_POST_INSTALL="rm -fv /usr/lib/libz.a"
PKG_SHA256="bb329a0a2cd0274d05519d61c667c062e06990d72e125ee2dfa8de64f0119d16"
