PKG_NAME="zstd"
PKG_VER="1.5.7"
PKG_URL1="https://github.com/facebook/zstd/releases/download/v${PKG_VER}/zstd-${PKG_VER}.tar.gz"
PKG_URL2=""
PKG_URL3=""
PKG_BUILD_TYPE="custom"
PKG_CUSTOM_BUILD="make prefix=/usr"
PKG_CUSTOM_INSTALL="make prefix=/usr install && rm -v /usr/lib/libzstd.a"
